"""FCCM guide with one newly inspected author manuscript and original exercises."""

FCCM_ROUTE = {
    "id": "fccm-2025",
    "title": "FCCM 2025: why parallel calculations can wait for memory",
    "coverage_status": "Limited guide; one externally inspected manuscript, official metadata for a second paper, broader review unfinished",
    "status": "Limited reading guide with one full Banked Memories walkthrough based on an externally inspected manuscript. High Throughput Matrix Transposition is retained as an abstract/metadata reading lead because its full paper was not available for this review. This is not a conference-wide synthesis or an independent implementation test.",
    "intro": "Suppose four calculations are ready to run, but each needs a number from memory. Can all four numbers arrive together? That depends on where they are stored, how many reads the storage can handle at once, and how the results travel back. An FPGA is a chip whose logic and connections can be configured after manufacture; that flexibility does not remove these limits. This guide starts with a small invented example, then connects it to one inspected paper. It is not a review of the whole conference.",
    "evidence": "The existing local audit reports 68 abstract-bearing metadata records and no locally validated PDFs. During course development, the author manuscript Banked Memories for Soft SIMT Processors, arXiv:2503.24132v1, was inspected online, including sections III–VI, and supplies the one full learner walkthrough. The official FCCM program and accepted-paper list confirm the identity and session placement of Banked Memories and High Throughput Matrix Transposition on HBM-Enabled FPGAs; the latter's DOI and abstract are recorded below, but its full paper was not inspected here. That is new external reading, not a retroactive change to the audit's local-file count. The remaining papers and other advertised sources have not received new full-text review here.",
    "themes": [
        {
            "title": "1. Count the reads that must wait for the same bank",
            "body": "A memory bank is a separately accessible section of storage. In this invented example, there are four banks, numbered 0 to 3, and each can start one read per clock cycle. A word is one fixed-size piece of stored data; its address identifies its position. To find its bank, divide the word address by four and take the remainder: address 5 belongs to bank 1. First count only the cycles needed to start all the reads. Leave out the time spent preparing requests, fetching the words, and delivering them. Each request below asks for a different word, so sharing one fetched word among several readers cannot help.",
            "subthemes": [
                ("Reads to different banks", "Addresses 0, 1, 2, and 3 use different banks. All four reads can start in the same cycle. Each bank has one request and can accept it immediately."),
                ("Reads to the same bank", "Addresses 0, 4, 8, and 12 all use bank 0. That bank must start them over four cycles; the other three banks cannot fetch its words for it. Addresses 0, 4, 1, and 5 need two cycles because banks 0 and 1 each receive two reads. Count the requests at each bank and take the largest count. Under this model, that is how many cycles are needed to start every read, not to deliver every result."),
            ],
            "reading": "Section III.A of Banked Memories for Soft SIMT Processors describes a controller that counts requests to each bank and uses the largest count to space out groups of requests. Section III.B gives each bank a rule for choosing its next waiting request; the paper calls that choice arbitration. Connections after the banks send each fetched word back to the calculation that asked for it. Counting requests, choosing one, and returning a word are distinct jobs. The paper reports five initial cycles before its first read operation is issued and a three-cycle delay inside a bank. Those are details of that design, not timing assumptions for the exercise below.",
            "lessons": [("s3", "Access rate"), ("s4", "Shared boundaries"), ("s7", "The slowest required participant")],
            "worked_example": [
                "Now restore one omitted limit. Suppose four requested words use different banks, but the path carrying results back can carry only two words per cycle. Give the banks a one-cycle read time and a buffer holding all four results. Reads issued in cycle 1 become available at the start of cycle 2. Two words return in cycle 2 and two in cycle 3. The last word arrives at the end of cycle 3. One cycle of bank service is not one cycle from request to delivery.",
                "For a long sequence of such groups, the return path can deliver at most two words per cycle even though the banks can produce four. A finite buffer cannot absorb that difference forever. Eventually the controller must stop issuing some reads. More buffer can postpone the stop; it cannot raise the sustained delivery rate. This is an invented extension of the teaching model, not a description of the paper's return network.",
            ],
            "practice": {
                "question": "Eight reads use addresses 0 through 7. Each bank handles one read per cycle, results become available the next cycle, and the shared return path carries two words per cycle. Assume enough buffering. What is the earliest final delivery cycle? Would doubling each bank's service capacity improve it?",
                "answer": "Each bank receives two reads, so bank service needs two cycles. Issue addresses 0–3 in cycle 1 and 4–7 in cycle 2. Return two words in each of cycles 2, 3, 4, and 5; the final delivery is at the end of cycle 5. Nothing can return before cycle 2, and eight words require four return cycles, so this schedule meets the lower bound. Doubling bank capacity lets all reads issue in cycle 1 but leaves the same earliest return and four-cycle return requirement. Final delivery remains cycle 5. These conclusions depend on the stated buffer and timing assumptions.",
            },
        },
        {
            "title": "2. Move the data, then count the cost of moving it",
            "body": "In the teaching model, store a four-by-four array row by row. Row zero has word addresses 0, 1, 2, 3, while column zero has 0, 4, 8, 12. Reading the row uses all banks; reading the column uses one. The mathematical array alone does not specify the cost of its physical layout.",
            "subthemes": [
                ("Leave a gap between rows", "Reserve five words per row instead of four, leaving one unused word after each row. This is called padding. Column zero now uses addresses 0, 5, 10, 15, which belong to four different banks. Its four reads can start together, but the reserved storage grows from 16 to 20 words, or 25%."),
                ("Include the copy and later readers", "If the array already exists, making this new arrangement may require a copy. Any later calculation must also know that rows now start five words apart. The stored positions change; the array's values and their row and column identities must not. Count the copying time and check both row and column reads before choosing the arrangement."),
            ],
            "reading": "The paper compares two kinds of access pattern across memory organizations. A matrix transpose swaps rows and columns, so it often turns nearby reads into far-apart reads. An FFT is a staged calculation used in signal processing whose later stages combine values from different positions. The results show that the preferred organization depends on the access pattern and storage footprint; adding banks does not automatically help every workload.",
            "lessons": [("s6", "Layout and transformation"), ("physical-design", "Storage and routing costs")],
            "worked_example": [
                "A reported result shows why the whole operation matters. In table II, for the 32-by-32 transpose, compare the two 16-bank columns. The paper changes which address bits choose a bank; it does not apply the padding example above. Read cycles fall from 168 to 106, but write cycles barely change: 1,054 to 1,050. Total cycles fall from 1,613 to 1,547. Calculating from those entries, reads use about 37% fewer cycles, while the total uses only about 4% fewer. Writes still account for about 68% of the new total. Improving reads leaves most of this workload's time untouched. These are reported cycle counts and our arithmetic, not a new board measurement or a result for every array size.",
                "Suppose converting the original array to the five-word row layout costs 12 service cycles. One later column read costs four cycles without padding and one with it. For n column reads, the original costs 4n cycles; conversion followed by padded reads costs 12 + n. Four reads tie at 16 cycles. Five reads are the first whole-number case that saves time: 20 cycles become 17. Assume the converted copy remains valid, the extra storage fits, and no conversion back is needed.",
                "If the array changes after every two column reads and rebuilding still costs 12 cycles, each pair costs 14 cycles with conversion versus eight without. Counting ten reads across five different versions as one reusable batch would hide four rebuilds. The converted layout is valid only until the original data changes, so that validity window matters as much as its per-read advantage.",
                "Padding also needs an address calculation. With six words reserved per row, column-zero addresses become 0, 6, 12, 18. Their bank numbers are 0, 2, 0, 2: two service cycles, not one. The reserved footprint is now 24 words. For this column and these banks, five-word rows use less storage and have fewer conflicts than six-word rows. More padding does not automatically lower the complete cost.",
            ],
            "practice": {
                "question": "For the same unchanged four-by-four array, suppose five-word rows cost 12 cycles to prepare and six-word rows cost only two. Later column reads cost one and two cycles respectively. Both layouts fit. Which option, including leaving the array unchanged, has the lowest cost for three reads? For twelve?",
                "answer": "For three reads, unchanged costs 4×3 = 12 cycles, five-word rows cost 12 + 3 = 15, and six-word rows cost 2 + 2×3 = 8. Six-word rows win despite their greater conflict count. For twelve reads, the costs are 48, 24, and 26 cycles: five-word rows win. The prepared layouts tie at ten reads because 12 + n = 2 + 2n. Their different setup costs change the choice. A storage limit below 24 words would exclude the six-word layout even when its timing is attractive.",
            },
        },
        {
            "title": "3. Fewer cycles need not mean less time",
            "body": "So far, a cycle has been a counting unit. Its duration matters too. Extra circuitry for choosing and connecting requests may force a lower clock rate. Before claiming that one design finishes sooner, convert its cycle count into elapsed time, include preparation, and check that it still returns the required answers. Then ask how the operating rate was established: assumed in a simulation, estimated by design tools, or measured on a running board.",
            "subthemes": [
                ("Cycles and elapsed time", "Eight cycles at 200 million cycles per second take 40 ns. Six cycles at 100 million per second take 60 ns. Fewer cycles can therefore be slower if the changed design runs at a lower rate. These are invented numbers."),
                ("Resource and evidence boundaries", "Count the limiting physical resource rather than one convenient component count. Also ask whether timings came from simulation, implementation tools, or a running board; this guide does not infer one from another."),
            ],
            "reading": "Sections IV.A and VI discuss physical footprint; section V reports workload comparisons. The manuscript says the goal is isolating memory-architecture effects, not finding the fastest possible FFT implementation. This course has not rerun its experiments. Its abstract reports 51 benchmarks, while section V says 52 combinations; that count discrepancy remains unresolved here.",
            "lessons": [("physical-design", "Timing and evidence"), ("s10", "Complete-path comparisons")],
            "worked_example": [
                "Use two invented designs. A takes eight cycles per group at 200 million cycles per second, often written 200 MHz. A hertz means one cycle per second; a megahertz means one million. One second contains one billion nanoseconds, so each cycle lasts 1,000,000,000 ÷ 200,000,000 = 5 ns. Eight cycles therefore take 8 × 5 = 40 ns. B takes six cycles at 100 million per second: each cycle lasts 10 ns, giving 60 ns for the group. Count cycles first, then multiply by the duration of a cycle; do not compare the counts without their clock rates.",
                "If B's extra controller work makes each cycle longer, its smaller cycle count does not compensate. With all other times unchanged, B must run above 150 million cycles per second to beat A: six cycles divided by 150 million cycles per second is 0.00000004 seconds, or exactly 40 ns. At that rate the designs tie; B needs a higher achievable rate to finish sooner.",
                "Now suppose preparing B costs 100 ns once, but B actually runs at 250 million cycles per second, making each group take 24 ns. A needs no preparation. For n groups processed sequentially, compare 40n with 100 + 24n ns. B first wins at seven groups: 268 ns versus A's 280 ns. For six groups, B takes 244 ns versus 240 ns. This assumes no overlap between preparation and execution and no other differences in delivery or checking.",
                "A timing calculation is conditional on the operating rate being achievable. A simulator given 250 million cycles per second can calculate behavior under that assumption; it does not establish that the placed and connected circuit meets that rate. Implementation-tool estimates and measurements from a running board provide different evidence. Also check whether the design fits the specific device: spare arithmetic units do not compensate for insufficient memory blocks or routing capacity.",
            ],
            "practice": {
                "question": "Keep A at 40 ns per group. B still takes six cycles and needs 100 ns of one-time preparation, but its achievable rate is only 125 million cycles per second. Can processing more groups make B faster under this model? What if the preparation happens before requests arrive?",
                "answer": "B now needs 48 ns per group, so its complete cost is 100 + 48n ns versus A's 40n. For every positive n it is slower; there is no batch size that recovers the setup cost. Preparing before arrival removes the 100 ns from the request's waiting time, but B still takes 48 rather than 40 ns per group. Report separately when preparation occurs and whether it is included in the measurement. Moving work outside the timer does not reduce its resource cost.",
            },
        },
    ],
    "exercise": "Under the four-bank teaching assumptions, eight reads target addresses 0, 4, 8, 1, 5, 2, 6, 3. Bank counts are 3, 2, 2, and 1, so three service cycles are required. Construct a schedule: cycle one serves 0, 1, 2, 3; cycle two serves 4, 5, 6; cycle three serves 8. Explain why eight reads divided by four banks gives only a two-cycle capacity lower bound, not an achievable schedule for these addresses.",
    "sources": [
        ("https://arxiv.org/html/2503.24132v1#S5.T2", "Table II — transpose cycle counts; compare the two 16-bank columns for the 32-by-32 matrix"),
        ("https://arxiv.org/html/2503.24132v1", "Langhammer and Constantinides, Banked Memories for Soft SIMT Processors — sections III–VI, author manuscript"),
        ("https://www.fccm.org/fccm-2025-program/", "Official FCCM 2025 program — Banked Memories listed in the Memories session"),
        ("https://www.fccm.org/accepted-paper-list-2025/", "Official FCCM 2025 accepted-paper list — High Throughput Matrix Transposition identity and authors"),
        ("https://doi.org/10.1109/FCCM62733.2025.00038", "High Throughput Matrix Transposition on HBM-Enabled FPGAs — DOI and publication record; full paper not inspected here"),
        ("analysis/fccm-2025-source-acquisition-audit.md", "Earlier local acquisition audit — no local PDFs at that audit boundary"),
    ],
}
