"""Original worked scientific-computing lesson; teaching values are not measurements."""

SCIENCE_LESSON = {
    "id": "scientific-workflow",
    "kicker": "Worked science",
    "title": "Finish a Scientific Calculation With a Result You Can Check",
    "summary": "Prerequisites: numerical precision, dependencies, memory, and coordination. Follow a small heat-flow calculation from physical assumptions to checked output, then account for a larger distributed solve.",
    "body": [
        "Suppose you want the settled temperature along a rod whose ends are held at 0 and 90 degrees. Assume uniform material, no heat produced inside, no heat escaping through the sides, and enough time to settle. These assumptions define the problem being solved. A real rod losing heat to the surrounding air would require a different model. Computing the wrong model more accurately does not repair that mismatch.",
        "Represent the rod by four equally spaced points: the two known ends and two unknown interior temperatures, u and v. In this simplified balance model, each interior temperature equals the average of its two neighbors. Therefore 2u − v = 0 and 2v − u = 90. The values u = 30 and v = 60 satisfy both equations. We have replaced a continuous object with a finite set of values; that replacement is called discretization. This special example agrees with the linear temperature profile under the stated ideal assumptions. It does not show that four points suffice for other heat problems.",
        "For a tiny system, we can solve the equations directly. To illustrate repeated approximation, start at u = 0, v = 0. In each round, compute the next u as old v divided by two, and the next v as (old u + 90) divided by two. Both use the old values, not a neighbor already changed during this round. The first guesses are (0, 45), (22.5, 45), (22.5, 56.25), and (28.125, 56.25). Each round is an iteration. Updating in place would define a different sequence and must not be silently substituted when comparing implementations.",
        "How do we decide when to stop without knowing the exact answer? Put a candidate back into the equations. Define its two residuals as 0 − (2u − v) and 90 − (2v − u): the amounts by which the candidate misses the required balances. At (28.125, 56.25), these are 0 and 5.625. For this lesson, the residual size is the larger absolute value. Our explicit rule accepts a solve when that size is at most 0.1 degree in these scaled balance equations. Merely reaching a time limit is not acceptance.",
        "In exact arithmetic, this particular iteration halves that residual size every round, starting from 90. After nine rounds it is 90/512, about 0.176, which fails. After ten it is 90/1024, about 0.088, which passes. The tenth guess is (29.970703125, 59.94140625). This is a derivation for these two equations and this initial guess, not a general convergence rate. A larger problem or another update rule needs its own analysis and measurements.",
        "A small residual is not automatically a small error in the answer. Consider a separate pair of scaled equations: u = 1 and 0.000001v = 0.000001. The exact answer is (1, 1), but the candidate (1, 0) has a largest residual of only 0.000001 while v is wrong by one whole unit. Multiplying the second equation by a million leaves its exact answer unchanged but changes that raw residual to one. Equation scaling and sensitivity therefore matter when translating an equation check into an accuracy claim. A residual test needs justification for the problem and quantity you care about.",
        "The PETSc solver documentation linked below gives a practical reason to record the stopping rule precisely. Its default test compares a residual norm with the larger of two limits: a relative limit based on a reference residual, and an absolute limit. For an invented example, let the reference residual be 100, the relative tolerance be 0.01, and the absolute tolerance be 0.1. The two limits are 1 and 0.1, so a residual norm of 0.5 passes the test. It is below the relative limit even though it is above the absolute limit. These numbers explain the rule; they are not PETSc's default settings or measurements from a paper.",
        "Passing that test does not mean the answer is within 0.5 of the exact answer. A residual measures how much the candidate misses the stated equations; the relation between that miss and the answer's error also depends on the equations. PETSc's residual norm may be preconditioned—transformed before measurement by an auxiliary calculation intended to make iteration easier—or otherwise depend on solver type and settings, so check which quantity was tested. By default, reaching the iteration limit is reported as failure, not convergence. The largest-component, at-most-0.1 rule in this lesson is a separate teaching rule, not PETSc's default. Interpret a success flag using the configured test and the recorded termination reason.",
        "Now move to a larger, hypothetical heat problem split across four workers. Each owns part of the grid and keeps copies of neighboring edge values needed for its next calculation. Those copies are often called a halo. Fresh edge values must arrive before dependent boundary work can use them. Sending fewer values by reusing an older edge can reduce traffic, but changes which mathematical update is performed. Overlapping exchange with independent interior work can preserve the update, provided the old and new values remain distinct and the boundary waits for the right round.",
        "Use the invented sequential timing model in the table. Reading and preparing the problem takes 2 seconds. Each of 1,000 iterations takes 5 ms of local work, 3 ms of neighbor exchange, and 2 ms to combine the workers' residual summaries and decide whether to continue. Thus the loop takes 10 seconds. A final independent equation check costs 1 second and writing the accepted result costs another. End-to-end time is 14 seconds. The two-point example establishes the meaning of the checks; it does not predict this larger problem's 1,000-iteration count.",
        "Compare two separate changes, keeping the same problem and acceptance rule. Change A halves only the 5-ms local work. Its loop takes 7.5 seconds and the whole job 11.5 seconds. Change B adds 1 second of preparation but, by a stipulated mathematical improvement, reaches acceptance in 600 iterations at the original 10 ms each. Its whole job takes 3 + 6 + 1 + 1 = 11 seconds. B wins despite having no faster iteration. Establishing that it actually needs only 600 iterations would require evidence; here that count is a teaching assumption.",
        "A third proposal uses fewer bits, reducing local work to 3 ms, but needs 1,400 iterations to pass the same check. Its loop takes 1,400 × (3 + 3 + 2) ms = 11.2 seconds, giving 15.2 seconds overall. It loses to the baseline. If rounding instead prevents it from passing the threshold at all, report a failed solve rather than a fast completion. Do not multiply the gains from these proposals: changing representation or the mathematical method may also change communication, iteration count, or the cost of checking.",
        "Finally, separate equation accuracy from scientific adequacy. A small equation residual says nothing by itself about omitted heat loss, uncertain boundary temperatures, or whether the chosen grid resolves changes that affect the reported quantity. For a real study, examine those assumptions, compare resolutions where appropriate, and check against analytic results or observations available for the problem. Agreement between two grids alone is not a proof of physical truth. Save the input conditions, model, grid, numerical settings, termination reason, final checks, and output together so another reader can tell what was actually established.",
        "This is the question to carry into the SC papers: what accepted result did the measured work produce? A faster data-transfer operation, a smaller compressed field, and a faster iterative solver affect different parts of the job. Compare them only after fixing the physical question, the permitted numerical error, and the timing boundary. Their individual evaluations are not evidence that a combined workflow has been run.",
    ],
    "table_after_paragraph": 9,
    "table": {
        "caption": "Invented larger-solve timing model: stages are sequential, with no overlap or failures.",
        "headings": ["Stage", "Elapsed time", "What must be established"],
        "rows": [
            ["Read and prepare", "0–2 s", "Inputs, grid, equations, and worker assignments are ready"],
            ["1,000 update rounds", "2–12 s", "Each round uses the required neighbor values and checks the stated stopping rule"],
            ["Independent final equation check", "12–13 s", "The returned values meet the required equation tolerance"],
            ["Write accepted output", "13–14 s", "Results and interpretation settings are available to the next consumer"],
        ],
    },
    "exercise": {
        "question": "In the 14-second baseline, suppose checking costs 2 ms and the remaining work costs 8 ms per iteration. A new schedule checks only every tenth iteration. Assume this does not change the updates, the candidate remains acceptable once it first passes, and the first passing iteration is 996. At which iteration does the schedule discover success? What is total job time? Why would a maximum-iteration stop at 990 not count as the same result?",
        "answer": "Success is discovered at iteration 1,000, after four extra updates. There are 1,000 × 8 ms = 8 seconds of update and exchange work, plus 100 × 2 ms = 0.2 seconds of checks. Adding the unchanged 4 seconds outside the loop gives 12.2 seconds. A limit at 990 stops before the first passing candidate, so it is a failure under the stated rule, not an equivalent faster solve. If acceptability does not persist, or checks change the update process, the supplied assumptions no longer justify this calculation.",
    },
    "sources": [
        ("https://petsc.org/release/manualpages/KSP/KSPConvergedDefault/", "PETSc: KSPConvergedDefault, Notes — stopping thresholds, residual configuration, and iteration-limit handling (consulted 21 September 2026)"),
        ("https://netlib.org/linalg/old_html_templates/section2.8.2.html", "Templates for the Solution of Linear Systems: Stopping Criteria — further reading on accuracy, progress, and work limits"),
        ("analysis/sc-2025-first-principles-synthesis.md", "SC 2025 synthesis — scientific workflows and numerical-method leads, with source-depth limits"),
    ],
    "applications": [
        "Numerical methods: compare time to the same justified acceptance condition, not just time per iteration.",
        "Distributed simulation: distinguish a legal overlap from an update using a different round's data.",
        "Scientific reporting: separate solving the chosen equations from establishing their adequacy for the real question.",
    ],
}
