/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:1" *)
module aimc_operation_partition(op_class, resident_weights, estimated_state_error, state_error_budget, attention_flip_rate, attention_flip_budget, token_flip_rate, token_flip_budget, calibration_age, weak_tiles, placement, reason);
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [1:0] _000_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _001_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [1:0] _002_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _003_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [1:0] _004_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _005_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [1:0] _006_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _007_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [1:0] _008_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _009_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [1:0] _010_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _011_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:50" *)
  wire [3:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire [1:0] _016_;
  wire [1:0] _017_;
  wire [1:0] _018_;
  wire [7:0] _019_;
  wire [3:0] _020_;
  wire [1:0] _021_;
  wire [3:0] _022_;
  wire [1:0] _023_;
  wire [3:0] _024_;
  wire [1:0] _025_;
  wire [3:0] _026_;
  wire [1:0] _027_;
  wire [3:0] _028_;
  wire [1:0] _029_;
  wire _030_;
  wire [3:0] _031_;
  wire [3:0] _032_;
  wire [3:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)
  wire _047_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)
  wire _048_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)
  wire _049_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire _050_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire _051_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire _052_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire _053_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)
  wire _054_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)
  wire _055_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)
  wire _056_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _057_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _058_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _059_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _060_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)
  wire _061_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)
  wire _062_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)
  wire _063_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)
  wire _064_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *)
  wire _065_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)
  wire _066_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)
  wire _067_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *)
  wire _068_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)
  wire _069_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire _070_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire _071_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)
  wire _072_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)
  wire _073_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _074_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _075_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)
  wire _076_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *)
  wire _077_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14" *)
  wire [15:0] _078_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _079_;
  wire [15:0] _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _085_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _086_;
  wire [7:0] _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *)
  wire [7:0] _092_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _093_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _094_;
  wire [7:0] _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *)
  wire [7:0] _099_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _100_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _101_;
  wire [7:0] _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *)
  wire [7:0] _106_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _107_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _108_;
  wire [7:0] _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _113_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _114_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _115_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _116_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _117_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _118_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _119_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _120_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _121_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _122_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _123_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _124_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _125_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _126_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _127_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _128_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _129_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _130_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _131_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _132_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _133_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _134_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _135_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _136_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _137_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _138_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _139_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _140_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _141_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _142_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _143_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _144_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)
  wire _145_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)
  wire [7:0] _146_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _147_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _148_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _149_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _150_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _151_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _152_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _153_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _154_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _155_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _156_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _157_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)
  wire [7:0] _158_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _159_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _160_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _161_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _162_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _163_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _164_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _165_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _166_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _167_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _168_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _169_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)
  wire [7:0] _170_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _171_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _172_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _173_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _174_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _175_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _176_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _177_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _178_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _179_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _180_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)
  wire _181_;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:7" *)
  input [7:0] attention_flip_budget;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:6" *)
  input [7:0] attention_flip_rate;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:10" *)
  input [15:0] calibration_age;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)
  wire digital_only;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:4" *)
  input [7:0] estimated_state_error;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)
  wire fixed_weight_op;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)
  wire hybrid_candidate;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:2" *)
  input [3:0] op_class;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:12" *)
  output [1:0] placement;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:13" *)
  output [3:0] reason;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:3" *)
  input resident_weights;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)
  wire stale_weak_tiles;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:5" *)
  input [7:0] state_error_budget;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:9" *)
  input [7:0] token_flip_budget;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:8" *)
  input [7:0] token_flip_rate;
  (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:11" *)
  input [7:0] weak_tiles;
  assign _034_ = _013_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)  _013_[1];
  assign _035_ = _014_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)  _014_[1];
  assign _036_ = _015_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)  _014_[1];
  assign _037_ = _013_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)  _016_[1];
  assign _038_ = _015_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)  _013_[1];
  assign _039_ = _017_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)  _014_[1];
  assign _040_ = _017_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _018_[1];
  assign _041_ = _013_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _018_[1];
  assign _042_ = _014_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _018_[1];
  assign _017_[0] = op_class[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  op_class[1];
  assign _016_[1] = _032_[2] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _033_[3];
  assign _043_ = _017_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _016_[1];
  assign _014_[0] = op_class[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  _032_[1];
  assign _013_[1] = op_class[2] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  op_class[3];
  assign _044_ = _014_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  _013_[1];
  assign _013_[0] = _031_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  op_class[1];
  assign _014_[1] = _032_[2] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  op_class[3];
  assign _045_ = _013_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  _014_[1];
  assign _015_[0] = _031_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  _032_[1];
  assign _018_[1] = op_class[2] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  _033_[3];
  assign _046_ = _015_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  _018_[1];
  assign _062_ = _089_ | _090_;
  assign _019_[0] = _079_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _080_[1];
  assign _020_[0] = _019_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _019_[1];
  assign _021_[0] = _020_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _020_[1];
  assign _083_ = _021_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _021_[1];
  assign _061_ = _082_ | _083_;
  assign _022_[0] = _086_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _087_[1];
  assign _023_[0] = _022_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _022_[1];
  assign _090_ = _023_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _023_[1];
  assign _024_[0] = _094_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _095_[1];
  assign _025_[0] = _024_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _024_[1];
  assign _025_[1] = _024_[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _024_[3];
  assign _097_ = _025_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _025_[1];
  assign _026_[0] = _101_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _102_[1];
  assign _026_[1] = _102_[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _102_[3];
  assign _027_[0] = _026_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _026_[1];
  assign _027_[1] = _026_[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _026_[3];
  assign _104_ = _027_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _027_[1];
  assign _028_[0] = _108_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _109_[1];
  assign _028_[1] = _109_[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _109_[3];
  assign _028_[3] = _109_[6] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _109_[7];
  assign _029_[0] = _028_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _028_[1];
  assign _029_[1] = _028_[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _028_[3];
  assign _111_ = _029_[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *)  _029_[1];
  assign _030_ = _017_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)  _013_[1];
  assign _047_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *) _034_;
  assign _048_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *) _035_;
  assign _049_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *) _036_;
  assign _052_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *) _037_;
  assign _054_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *) _030_;
  assign _055_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *) _038_;
  assign _056_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *) _039_;
  assign _057_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *) _040_;
  assign _058_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *) _041_;
  assign _059_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *) _042_;
  assign _060_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *) _043_;
  assign _068_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) resident_weights;
  assign _053_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) _044_;
  assign _050_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) _045_;
  assign _051_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) _046_;
  assign stale_weak_tiles = _061_ &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *)  _062_;
  assign fixed_weight_op = _069_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)  _049_;
  assign _069_ = _047_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:45" *)  _048_;
  assign _071_ = _070_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)  _051_;
  assign _072_ = _054_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)  _055_;
  assign hybrid_candidate = _071_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:46" *)  _052_;
  assign _073_ = _072_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:47" *)  _056_;
  assign _074_ = _073_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _057_;
  assign _075_ = _074_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _058_;
  assign _076_ = _075_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _059_;
  assign digital_only = _076_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:48" *)  _060_;
  assign _065_ = _068_ &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *)  _077_;
  assign _066_ = _070_ &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  _063_;
  assign _077_ = fixed_weight_op |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *)  hybrid_candidate;
  assign _070_ = _053_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  _050_;
  assign _067_ = _051_ &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  _064_;
  assign _012_[3] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:75" *) hybrid_candidate;
  assign _011_[0] = fixed_weight_op ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:72" *) 1'h1 : _012_[3];
  assign _011_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:72" *) fixed_weight_op;
  assign _011_[3] = fixed_weight_op ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:72" *) 1'h0 : _012_[3];
  assign _010_[1] = fixed_weight_op ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:72" *) 1'h0 : hybrid_candidate;
  assign _009_[0] = _067_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) 1'h0 : _011_[0];
  assign _009_[1] = _067_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) 1'h1 : _011_[1];
  assign _009_[2] = _067_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) 1'h1 : _011_[3];
  assign _009_[3] = _067_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) 1'h0 : _011_[3];
  assign _008_[0] = _067_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) 1'h0 : fixed_weight_op;
  assign _008_[1] = _067_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *) 1'h0 : _010_[1];
  assign _007_[0] = _066_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) 1'h1 : _009_[0];
  assign _007_[1] = _066_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) 1'h0 : _009_[1];
  assign _007_[2] = _066_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) 1'h1 : _009_[2];
  assign _007_[3] = _066_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) 1'h0 : _009_[3];
  assign _006_[0] = _066_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) 1'h0 : _008_[0];
  assign _006_[1] = _066_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *) 1'h0 : _008_[1];
  assign _005_[0] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:63" *) 1'h1 : _007_[0];
  assign _005_[1] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:63" *) 1'h1 : _007_[1];
  assign _005_[2] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:63" *) 1'h1 : _007_[2];
  assign _005_[3] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:63" *) 1'h0 : _007_[3];
  assign _004_[0] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:63" *) 1'h0 : _006_[0];
  assign _004_[1] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:63" *) 1'h0 : _006_[1];
  assign _003_[0] = _098_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _005_[0] : 1'h0;
  assign _003_[1] = _098_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _005_[1] : 1'h0;
  assign _003_[2] = _098_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _005_[2] : 1'h1;
  assign _003_[3] = _098_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _005_[3] : 1'h0;
  assign _002_[0] = _098_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _004_[0] : 1'h0;
  assign _002_[1] = _098_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _004_[1] : 1'h0;
  assign _000_[0] = _065_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) 1'h0 : _002_[0];
  assign _000_[1] = _065_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) 1'h0 : _002_[1];
  assign _001_[0] = _065_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) 1'h1 : _003_[0];
  assign _001_[1] = _065_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) 1'h1 : _003_[1];
  assign _001_[2] = _065_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) 1'h0 : _003_[2];
  assign _001_[3] = _065_ ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:57" *) 1'h0 : _003_[3];
  assign reason[0] = digital_only ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:54" *) 1'h0 : _001_[0];
  assign reason[1] = digital_only ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:54" *) 1'h0 : _001_[1];
  assign reason[2] = digital_only ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:54" *) 1'h0 : _001_[2];
  assign reason[3] = digital_only ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:54" *) 1'h0 : _001_[3];
  assign placement[0] = digital_only ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:54" *) 1'h0 : _000_[0];
  assign placement[1] = digital_only ? (* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:54" *) 1'h0 : _000_[1];
  assign _092_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[0];
  assign _092_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[1];
  assign _092_[2] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[2];
  assign _092_[3] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[3];
  assign _092_[4] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[4];
  assign _092_[5] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[5];
  assign _092_[6] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[6];
  assign _092_[7] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) state_error_budget[7];
  assign _099_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[0];
  assign _099_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[1];
  assign _099_[2] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[2];
  assign _099_[3] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[3];
  assign _099_[4] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[4];
  assign _099_[5] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[5];
  assign _099_[6] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[6];
  assign _099_[7] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) attention_flip_budget[7];
  assign _106_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[0];
  assign _106_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[1];
  assign _106_[2] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[2];
  assign _106_[3] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[3];
  assign _106_[4] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[4];
  assign _106_[5] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[5];
  assign _106_[6] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[6];
  assign _106_[7] = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:258" *) token_flip_budget[7];
  assign _082_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *) _084_;
  assign _081_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *) _078_[15];
  assign _089_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *) _091_;
  assign _088_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44" *) _085_[7];
  assign _096_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _093_[7];
  assign _063_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _105_;
  assign _103_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _100_[7];
  assign _064_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _112_;
  assign _110_ = ~(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60" *) _107_[7];
  assign _094_[0] = estimated_state_error[0] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[0];
  assign _095_[1] = estimated_state_error[1] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[1];
  assign _095_[2] = estimated_state_error[2] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[2];
  assign _095_[3] = estimated_state_error[3] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[3];
  assign _095_[4] = estimated_state_error[4] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[4];
  assign _095_[5] = estimated_state_error[5] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[5];
  assign _095_[6] = estimated_state_error[6] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[6];
  assign _095_[7] = estimated_state_error[7] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _092_[7];
  assign _158_[0] = attention_flip_rate[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[0];
  assign _158_[1] = attention_flip_rate[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[1];
  assign _158_[2] = attention_flip_rate[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[2];
  assign _158_[3] = attention_flip_rate[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[3];
  assign _158_[4] = attention_flip_rate[4] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[4];
  assign _158_[5] = attention_flip_rate[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[5];
  assign _158_[6] = attention_flip_rate[6] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[6];
  assign _158_[7] = attention_flip_rate[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _099_[7];
  assign _101_[0] = attention_flip_rate[0] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[0];
  assign _102_[1] = attention_flip_rate[1] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[1];
  assign _102_[2] = attention_flip_rate[2] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[2];
  assign _102_[3] = attention_flip_rate[3] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[3];
  assign _102_[4] = attention_flip_rate[4] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[4];
  assign _102_[5] = attention_flip_rate[5] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[5];
  assign _102_[6] = attention_flip_rate[6] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[6];
  assign _102_[7] = attention_flip_rate[7] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _099_[7];
  assign _170_[0] = token_flip_rate[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[0];
  assign _170_[1] = token_flip_rate[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[1];
  assign _170_[2] = token_flip_rate[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[2];
  assign _170_[3] = token_flip_rate[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[3];
  assign _170_[4] = token_flip_rate[4] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[4];
  assign _170_[5] = token_flip_rate[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[5];
  assign _170_[6] = token_flip_rate[6] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[6];
  assign _170_[7] = token_flip_rate[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _106_[7];
  assign _108_[0] = token_flip_rate[0] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[0];
  assign _109_[1] = token_flip_rate[1] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[1];
  assign _109_[2] = token_flip_rate[2] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[2];
  assign _109_[3] = token_flip_rate[3] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[3];
  assign _109_[4] = token_flip_rate[4] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[4];
  assign _109_[5] = token_flip_rate[5] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[5];
  assign _109_[6] = token_flip_rate[6] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[6];
  assign _109_[7] = token_flip_rate[7] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:262" *)  _106_[7];
  assign _113_ = _080_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _078_[0];
  assign _114_ = _080_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[2];
  assign _115_ = _080_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[4];
  assign _116_ = _080_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[6];
  assign _117_ = _080_[9] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[8];
  assign _118_ = _080_[13] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[12];
  assign _119_ = _080_[15] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[14];
  assign _120_ = _019_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _078_[1];
  assign _121_ = _019_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _128_;
  assign _122_ = _019_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _130_;
  assign _123_ = _019_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _131_;
  assign _124_ = _020_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _078_[3];
  assign _125_ = _020_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _134_;
  assign _126_ = _021_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _078_[7];
  assign _019_[1] = _080_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _080_[2];
  assign _019_[2] = _080_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _080_[4];
  assign _019_[3] = _080_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _080_[6];
  assign _019_[4] = _080_[9] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _080_[8];
  assign _019_[5] = _080_[11] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  calibration_age[10];
  assign _019_[6] = _080_[13] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _080_[12];
  assign _019_[7] = _080_[15] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _080_[14];
  assign _020_[1] = _019_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _019_[2];
  assign _020_[2] = _019_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _019_[4];
  assign _020_[3] = _019_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _019_[6];
  assign _021_[1] = _020_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _020_[2];
  assign _078_[0] = calibration_age[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:212" *)  _079_[0];
  assign _078_[1] = calibration_age[1] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _113_;
  assign _127_ = calibration_age[3] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _114_;
  assign _128_ = calibration_age[5] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _115_;
  assign _129_ = calibration_age[7] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _116_;
  assign _130_ = calibration_age[9] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _117_;
  assign _131_ = calibration_age[13] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _118_;
  assign _132_ = calibration_age[15] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _119_;
  assign _078_[3] = _127_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _120_;
  assign _133_ = _129_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _121_;
  assign _134_ = calibration_age[11] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _122_;
  assign _135_ = _132_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _123_;
  assign _078_[7] = _133_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _124_;
  assign _136_ = _135_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _125_;
  assign _078_[15] = _136_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _126_;
  assign _137_ = _087_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _085_[0];
  assign _138_ = _087_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  weak_tiles[4];
  assign _139_ = _087_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  weak_tiles[6];
  assign _140_ = _022_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _085_[1];
  assign _141_ = _022_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _143_;
  assign _142_ = _023_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _085_[3];
  assign _022_[1] = _087_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  weak_tiles[2];
  assign _022_[2] = _087_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _087_[4];
  assign _022_[3] = _087_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _087_[6];
  assign _023_[1] = _022_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:222" *)  _022_[2];
  assign _085_[0] = weak_tiles[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:212" *)  _086_[0];
  assign _085_[1] = weak_tiles[1] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _137_;
  assign _143_ = weak_tiles[5] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _138_;
  assign _144_ = weak_tiles[7] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _139_;
  assign _085_[3] = weak_tiles[3] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _140_;
  assign _145_ = _144_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _141_;
  assign _085_[7] = _145_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:260|<techmap.v>:221" *)  _142_;
  assign _147_ = _095_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _093_[0];
  assign _148_ = _095_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _146_[2];
  assign _149_ = _095_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _146_[4];
  assign _150_ = _095_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _146_[6];
  assign _151_ = _024_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _093_[1];
  assign _152_ = _024_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _155_;
  assign _153_ = _025_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _093_[3];
  assign _024_[1] = _095_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:222" *)  _095_[2];
  assign _024_[2] = _095_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:222" *)  _095_[4];
  assign _024_[3] = _095_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:222" *)  _095_[6];
  assign _093_[0] = _146_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:212" *)  _094_[0];
  assign _093_[1] = _146_[1] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _147_;
  assign _154_ = _146_[3] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _148_;
  assign _155_ = _146_[5] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _149_;
  assign _156_ = _146_[7] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _150_;
  assign _093_[3] = _154_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _151_;
  assign _157_ = _156_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _152_;
  assign _093_[7] = _157_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _153_;
  assign _159_ = _102_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _100_[0];
  assign _160_ = _102_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _158_[2];
  assign _161_ = _102_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _158_[4];
  assign _162_ = _102_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _158_[6];
  assign _163_ = _026_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _100_[1];
  assign _164_ = _026_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _167_;
  assign _165_ = _027_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _100_[3];
  assign _026_[2] = _102_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:222" *)  _102_[4];
  assign _026_[3] = _102_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:222" *)  _102_[6];
  assign _100_[0] = _158_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:212" *)  _101_[0];
  assign _100_[1] = _158_[1] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _159_;
  assign _166_ = _158_[3] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _160_;
  assign _167_ = _158_[5] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _161_;
  assign _168_ = _158_[7] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _162_;
  assign _100_[3] = _166_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _163_;
  assign _169_ = _168_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _164_;
  assign _100_[7] = _169_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _165_;
  assign _171_ = _109_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _107_[0];
  assign _172_ = _109_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _170_[2];
  assign _173_ = _109_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _170_[4];
  assign _174_ = _109_[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _170_[6];
  assign _175_ = _028_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _107_[1];
  assign _176_ = _028_[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _179_;
  assign _177_ = _029_[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _107_[3];
  assign _028_[2] = _109_[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:222" *)  _109_[4];
  assign _107_[0] = _170_[0] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:212" *)  _108_[0];
  assign _107_[1] = _170_[1] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _171_;
  assign _178_ = _170_[3] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _172_;
  assign _179_ = _170_[5] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _173_;
  assign _180_ = _170_[7] |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _174_;
  assign _107_[3] = _178_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _175_;
  assign _181_ = _180_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _176_;
  assign _107_[7] = _181_ |(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69|../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260|<techmap.v>:221" *)  _177_;
  assign _032_[2] = op_class[2] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:66" *)  1'h1;
  assign _031_[0] = op_class[0] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  1'h1;
  assign _032_[1] = op_class[1] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  1'h1;
  assign _033_[3] = op_class[3] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:69" *)  1'h1;
  assign _084_ = _081_ | _083_;
  assign _091_ = _088_ | _090_;
  assign _098_ = _096_ | _097_;
  assign _105_ = _103_ | _104_;
  assign _112_ = _110_ | _111_;
  assign _079_[0] = calibration_age[0] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[1] = calibration_age[1] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[2] = calibration_age[2] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[3] = calibration_age[3] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[4] = calibration_age[4] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[5] = calibration_age[5] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[6] = calibration_age[6] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[7] = calibration_age[7] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[8] = calibration_age[8] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[9] = calibration_age[9] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[11] = calibration_age[11] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[12] = calibration_age[12] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[13] = calibration_age[13] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[14] = calibration_age[14] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _080_[15] = calibration_age[15] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _086_[0] = weak_tiles[0] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _087_[1] = weak_tiles[1] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _087_[3] = weak_tiles[3] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _087_[4] = weak_tiles[4] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _087_[5] = weak_tiles[5] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _087_[6] = weak_tiles[6] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _087_[7] = weak_tiles[7] ^(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:44|<techmap.v>:262" *)  1'h1;
  assign _146_[0] = estimated_state_error[0] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[0];
  assign _146_[1] = estimated_state_error[1] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[1];
  assign _146_[2] = estimated_state_error[2] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[2];
  assign _146_[3] = estimated_state_error[3] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[3];
  assign _146_[4] = estimated_state_error[4] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[4];
  assign _146_[5] = estimated_state_error[5] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[5];
  assign _146_[6] = estimated_state_error[6] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[6];
  assign _146_[7] = estimated_state_error[7] &(* src = "../aimc-control-plane-rtl/aimc_operation_partition.v:60|<techmap.v>:260" *)  _092_[7];
  assign _010_[0] = fixed_weight_op;
  assign _011_[2] = _011_[3];
  assign _012_[2:0] = { _012_[3], 1'h1, _012_[3] };
  assign _015_[1] = _014_[1];
  assign _016_[0] = _013_[0];
  assign _017_[1] = _014_[1];
  assign _018_[0] = _017_[0];
  assign _031_[3:1] = op_class[3:1];
  assign { _032_[3], _032_[0] } = { op_class[3], op_class[0] };
  assign _033_[2:0] = { _032_[2], op_class[1], _031_[0] };
  assign { _080_[10], _080_[0] } = { calibration_age[10], _079_[0] };
  assign { _087_[2], _087_[0] } = { weak_tiles[2], _086_[0] };
  assign _095_[0] = _094_[0];
  assign _102_[0] = _101_[0];
  assign _109_[0] = _108_[0];
endmodule
