/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:1" *)
module aimc_control_plane(clk, rst_n, phase_decode, batch_size, active_context, resident_weights, healthy_tiles, weak_tiles, calibration_age, estimated_error, error_budget, path, reason);
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  wire [1:0] _000_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  wire [2:0] _001_;
  wire [1:0] _002_;
  wire [7:0] _003_;
  wire [3:0] _004_;
  wire [1:0] _005_;
  wire [7:0] _006_;
  wire [3:0] _007_;
  wire [1:0] _008_;
  wire [3:0] _009_;
  wire [1:0] _010_;
  wire [3:0] _011_;
  wire [1:0] _012_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *)
  wire _013_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)
  wire _014_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)
  wire _015_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)
  wire _016_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)
  wire _017_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)
  wire _018_;
  wire [2:0] _019_;
  wire [2:0] _020_;
  wire [2:0] _021_;
  wire [2:0] _022_;
  wire [1:0] _023_;
  wire [1:0] _024_;
  wire [1:0] _025_;
  wire [1:0] _026_;
  wire [1:0] _027_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [3:0] _028_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _029_;
  wire [3:0] _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14" *)
  wire [15:0] _034_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _035_;
  wire [15:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14" *)
  wire [15:0] _041_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _042_;
  wire [15:0] _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _048_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _049_;
  wire [7:0] _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *)
  wire [7:0] _055_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _056_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _057_;
  wire [7:0] _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _062_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _063_;
  wire [7:0] _064_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28|<techmap.v>:260|<techmap.v>:221" *)
  wire _065_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28|<techmap.v>:260|<techmap.v>:221" *)
  wire _066_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _067_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _068_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _069_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _070_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _071_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _072_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _073_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _074_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _075_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _076_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _077_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _078_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _079_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _080_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _081_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _082_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _083_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _084_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _085_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _086_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _087_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _088_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _089_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _090_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _091_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _092_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _093_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _094_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _095_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _096_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _097_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _098_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _099_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _100_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _101_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _102_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _103_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _104_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _105_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _106_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _107_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _108_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _109_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _110_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _111_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _112_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _113_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _114_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _115_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _116_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _117_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _118_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _119_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _120_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _121_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _122_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _123_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)
  wire _124_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)
  wire [7:0] _125_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _126_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _127_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _128_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _129_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _130_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _131_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _132_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _133_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _134_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _135_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)
  wire _136_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _137_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _138_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _139_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _140_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _141_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _142_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)
  wire _143_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)
  wire _144_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)
  wire _145_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)
  wire _146_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _147_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _148_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)
  wire _149_;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:6" *)
  input [15:0] active_context;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:5" *)
  input [3:0] batch_size;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *)
  wire batched_decode;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:10" *)
  input [15:0] calibration_age;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:2" *)
  input clk;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:12" *)
  input [7:0] error_budget;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:11" *)
  input [7:0] estimated_error;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:8" *)
  input [7:0] healthy_tiles;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)
  wire long_context_single_decode;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:13" *)
  output [1:0] path;
  reg [1:0] path;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:4" *)
  input phase_decode;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:14" *)
  output [2:0] reason;
  reg [2:0] reason;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:7" *)
  input resident_weights;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:3" *)
  input rst_n;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)
  wire stale_weak_tiles;
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:9" *)
  input [7:0] weak_tiles;
  assign _002_[0] = _029_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *)  _030_[1];
  assign _032_ = _002_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *)  _002_[1];
  assign _013_ = _031_ | _032_;
  assign _003_[0] = _035_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _036_[1];
  assign _004_[0] = _003_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _003_[1];
  assign _005_[0] = _004_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _004_[1];
  assign _039_ = _005_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _005_[1];
  assign _014_ = _038_ | _039_;
  assign _006_[0] = _042_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _043_[1];
  assign _007_[0] = _006_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _006_[1];
  assign _008_[0] = _007_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _007_[1];
  assign _046_ = _008_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _008_[1];
  assign _015_ = _045_ | _046_;
  assign _009_[0] = _049_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)  _050_[1];
  assign _010_[0] = _009_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)  _009_[1];
  assign _053_ = _010_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)  _010_[1];
  assign _016_ = _052_ | _053_;
  assign _011_[0] = _057_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *)  _058_[1];
  assign _012_[0] = _011_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *)  _011_[1];
  assign _060_ = _012_[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *)  _012_[1];
  assign batched_decode = phase_decode &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *)  _013_;
  assign _017_ = phase_decode &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _018_;
  assign long_context_single_decode = _017_ &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *)  _014_;
  assign stale_weak_tiles = _015_ &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *)  _016_;
  assign _019_[1] = long_context_single_decode ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:48" *) 1'h0 : batched_decode;
  assign _019_[2] = long_context_single_decode ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:48" *) 1'h1 : batched_decode;
  assign _020_[0] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:45" *) 1'h0 : long_context_single_decode;
  assign _020_[1] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:45" *) 1'h0 : _019_[1];
  assign _020_[2] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:45" *) 1'h1 : _019_[2];
  assign _021_[0] = _061_ ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *) _020_[0] : 1'h1;
  assign _021_[1] = _061_ ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *) _020_[1] : 1'h1;
  assign _021_[2] = _061_ ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *) _020_[2] : 1'h0;
  assign _022_[0] = _062_[7] ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39" *) _021_[0] : 1'h0;
  assign _022_[1] = _062_[7] ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39" *) _021_[1] : 1'h1;
  assign _022_[2] = _062_[7] ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39" *) _021_[2] : 1'h0;
  assign _001_[0] = resident_weights ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:36" *) _022_[0] : 1'h1;
  assign _001_[1] = resident_weights ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:36" *) _022_[1] : 1'h0;
  assign _001_[2] = resident_weights ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:36" *) _022_[2] : 1'h0;
  assign _025_[0] = stale_weak_tiles ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:45" *) 1'h0 : _024_[0];
  assign _023_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:51" *) batched_decode;
  assign _024_[0] = long_context_single_decode ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:48" *) 1'h0 : _023_[0];
  assign _026_[0] = _061_ ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *) _025_[0] : 1'h0;
  assign _026_[1] = _061_ ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *) _020_[1] : 1'h0;
  assign _027_[0] = _062_[7] ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39" *) _026_[0] : 1'h0;
  assign _027_[1] = _062_[7] ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39" *) _026_[1] : 1'h0;
  assign _000_[0] = resident_weights ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:36" *) _027_[0] : 1'h0;
  assign _000_[1] = resident_weights ? (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:36" *) _027_[1] : 1'h0;
  assign _031_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *) _033_;
  assign _018_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:28" *) _028_[3];
  assign _038_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *) _040_;
  assign _037_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29" *) _034_[15];
  assign _045_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29" *) _047_;
  assign _044_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29" *) _041_[15];
  assign _052_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *) _054_;
  assign _051_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30" *) _048_[7];
  assign _059_ = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42" *) _056_[7];
  assign _055_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[0];
  assign _055_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[1];
  assign _055_[2] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[2];
  assign _055_[3] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[3];
  assign _055_[4] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[4];
  assign _055_[5] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[5];
  assign _055_[6] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[6];
  assign _055_[7] = ~(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:258" *) error_budget[7];
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      path[0] <= 0;
    else
      path[0] <= _000_[0];
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      path[1] <= 0;
    else
      path[1] <= _000_[1];
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      reason[0] <= 1;
    else
      reason[0] <= _001_[0];
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      reason[1] <= 0;
    else
      reason[1] <= _001_[1];
  (* src = "../aimc-control-plane-rtl/aimc_control_plane.v:32" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      reason[2] <= 0;
    else
      reason[2] <= _001_[2];
  assign _126_ = _058_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _056_[0];
  assign _127_ = _058_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _125_[2];
  assign _128_ = _058_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _125_[4];
  assign _129_ = _058_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _125_[6];
  assign _130_ = _011_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _056_[1];
  assign _131_ = _011_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _134_;
  assign _132_ = _012_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _056_[3];
  assign _011_[1] = _058_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:222" *)  _058_[2];
  assign _011_[2] = _058_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:222" *)  _058_[4];
  assign _011_[3] = _058_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:222" *)  _058_[6];
  assign _012_[1] = _011_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:222" *)  _011_[2];
  assign _056_[0] = _125_[0] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:212" *)  _057_[0];
  assign _056_[1] = _125_[1] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _126_;
  assign _133_ = _125_[3] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _127_;
  assign _134_ = _125_[5] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _128_;
  assign _135_ = _125_[7] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _129_;
  assign _056_[3] = _133_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _130_;
  assign _136_ = _135_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _131_;
  assign _056_[7] = _136_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260|<techmap.v>:221" *)  _132_;
  assign _137_ = _064_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _062_[0];
  assign _138_ = _064_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  healthy_tiles[2];
  assign _139_ = _064_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  healthy_tiles[4];
  assign _140_ = _143_ &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _062_[1];
  assign _141_ = _145_ &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _148_;
  assign _142_ = _146_ &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _062_[3];
  assign _143_ = _064_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)  _064_[2];
  assign _144_ = _064_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)  _064_[4];
  assign _145_ = _064_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)  healthy_tiles[6];
  assign _146_ = _145_ &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:222" *)  _144_;
  assign _062_[0] = healthy_tiles[0] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:212" *)  _063_[0];
  assign _062_[1] = healthy_tiles[1] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _137_;
  assign _147_ = healthy_tiles[3] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _138_;
  assign _148_ = healthy_tiles[5] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _139_;
  assign _062_[3] = _147_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _140_;
  assign _149_ = healthy_tiles[7] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _141_;
  assign _062_[7] = _149_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:260|<techmap.v>:221" *)  _142_;
  assign _033_ = _018_ | _032_;
  assign _040_ = _037_ | _039_;
  assign _047_ = _044_ | _046_;
  assign _054_ = _051_ | _053_;
  assign _061_ = _059_ | _060_;
  assign _029_[0] = batch_size[0] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _030_[1] = batch_size[1] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _030_[3] = batch_size[3] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _035_[0] = active_context[0] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[1] = active_context[1] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[2] = active_context[2] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[3] = active_context[3] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[4] = active_context[4] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[5] = active_context[5] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[6] = active_context[6] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[7] = active_context[7] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[8] = active_context[8] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[9] = active_context[9] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[10] = active_context[10] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[11] = active_context[11] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[12] = active_context[12] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[14] = active_context[14] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _036_[15] = active_context[15] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _042_[0] = calibration_age[0] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[1] = calibration_age[1] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[2] = calibration_age[2] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[3] = calibration_age[3] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[4] = calibration_age[4] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[5] = calibration_age[5] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[6] = calibration_age[6] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[7] = calibration_age[7] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[8] = calibration_age[8] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[9] = calibration_age[9] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[11] = calibration_age[11] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[12] = calibration_age[12] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[13] = calibration_age[13] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[14] = calibration_age[14] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _043_[15] = calibration_age[15] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:262" *)  1'h1;
  assign _049_[0] = weak_tiles[0] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _050_[1] = weak_tiles[1] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _050_[3] = weak_tiles[3] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _050_[4] = weak_tiles[4] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _050_[5] = weak_tiles[5] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _050_[6] = weak_tiles[6] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _050_[7] = weak_tiles[7] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:262" *)  1'h1;
  assign _125_[0] = estimated_error[0] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[0];
  assign _125_[1] = estimated_error[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[1];
  assign _125_[2] = estimated_error[2] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[2];
  assign _125_[3] = estimated_error[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[3];
  assign _125_[4] = estimated_error[4] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[4];
  assign _125_[5] = estimated_error[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[5];
  assign _125_[6] = estimated_error[6] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[6];
  assign _125_[7] = estimated_error[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:260" *)  _055_[7];
  assign _057_[0] = estimated_error[0] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[0];
  assign _058_[1] = estimated_error[1] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[1];
  assign _058_[2] = estimated_error[2] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[2];
  assign _058_[3] = estimated_error[3] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[3];
  assign _058_[4] = estimated_error[4] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[4];
  assign _058_[5] = estimated_error[5] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[5];
  assign _058_[6] = estimated_error[6] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[6];
  assign _058_[7] = estimated_error[7] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:42|<techmap.v>:262" *)  _055_[7];
  assign _063_[0] = healthy_tiles[0] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _064_[1] = healthy_tiles[1] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _064_[2] = healthy_tiles[2] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _064_[3] = healthy_tiles[3] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _064_[4] = healthy_tiles[4] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _064_[5] = healthy_tiles[5] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _064_[7] = healthy_tiles[7] ^(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:39|<techmap.v>:262" *)  1'h1;
  assign _065_ = _030_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _028_[0];
  assign _066_ = _002_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _028_[1];
  assign _002_[1] = _030_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  batch_size[2];
  assign _028_[0] = batch_size[0] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:212" *)  _029_[0];
  assign _028_[1] = batch_size[1] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _065_;
  assign _028_[3] = batch_size[3] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _066_;
  assign _067_ = _036_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _034_[0];
  assign _068_ = _036_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[2];
  assign _069_ = _036_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[4];
  assign _070_ = _036_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[6];
  assign _071_ = _036_[9] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[8];
  assign _072_ = _036_[11] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[10];
  assign _073_ = active_context[13] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[12];
  assign _074_ = _036_[15] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  active_context[14];
  assign _075_ = _003_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _034_[1];
  assign _076_ = _003_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _083_;
  assign _077_ = _003_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _085_;
  assign _078_ = _003_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _073_;
  assign _079_ = _004_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _034_[3];
  assign _080_ = _004_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _089_;
  assign _081_ = _005_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _034_[7];
  assign _003_[1] = _036_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[2];
  assign _003_[2] = _036_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[4];
  assign _003_[3] = _036_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[6];
  assign _003_[4] = _036_[9] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[8];
  assign _003_[5] = _036_[11] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[10];
  assign _003_[6] = active_context[13] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[12];
  assign _003_[7] = _036_[15] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _036_[14];
  assign _004_[1] = _003_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _003_[2];
  assign _004_[2] = _003_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _003_[4];
  assign _004_[3] = _003_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _003_[6];
  assign _005_[1] = _004_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _004_[2];
  assign _034_[0] = active_context[0] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:212" *)  _035_[0];
  assign _034_[1] = active_context[1] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _067_;
  assign _082_ = active_context[3] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _068_;
  assign _083_ = active_context[5] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _069_;
  assign _084_ = active_context[7] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _070_;
  assign _085_ = active_context[9] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _071_;
  assign _086_ = active_context[11] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _072_;
  assign _087_ = active_context[15] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _074_;
  assign _034_[3] = _082_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _075_;
  assign _088_ = _084_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _076_;
  assign _089_ = _086_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _077_;
  assign _090_ = _087_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _078_;
  assign _034_[7] = _088_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _079_;
  assign _091_ = _090_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _080_;
  assign _034_[15] = _091_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _081_;
  assign _092_ = _043_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _041_[0];
  assign _093_ = _043_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[2];
  assign _094_ = _043_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[4];
  assign _095_ = _043_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[6];
  assign _096_ = _043_[9] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[8];
  assign _097_ = _043_[13] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[12];
  assign _098_ = _043_[15] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  calibration_age[14];
  assign _099_ = _006_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _041_[1];
  assign _100_ = _006_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _107_;
  assign _101_ = _006_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _109_;
  assign _102_ = _006_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _110_;
  assign _103_ = _007_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _041_[3];
  assign _104_ = _007_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _113_;
  assign _105_ = _008_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _041_[7];
  assign _006_[1] = _043_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _043_[2];
  assign _006_[2] = _043_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _043_[4];
  assign _006_[3] = _043_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _043_[6];
  assign _006_[4] = _043_[9] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _043_[8];
  assign _006_[5] = _043_[11] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  calibration_age[10];
  assign _006_[6] = _043_[13] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _043_[12];
  assign _006_[7] = _043_[15] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _043_[14];
  assign _007_[1] = _006_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _006_[2];
  assign _007_[2] = _006_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _006_[4];
  assign _007_[3] = _006_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _006_[6];
  assign _008_[1] = _007_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:222" *)  _007_[2];
  assign _041_[0] = calibration_age[0] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:212" *)  _042_[0];
  assign _041_[1] = calibration_age[1] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _092_;
  assign _106_ = calibration_age[3] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _093_;
  assign _107_ = calibration_age[5] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _094_;
  assign _108_ = calibration_age[7] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _095_;
  assign _109_ = calibration_age[9] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _096_;
  assign _110_ = calibration_age[13] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _097_;
  assign _111_ = calibration_age[15] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _098_;
  assign _041_[3] = _106_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _099_;
  assign _112_ = _108_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _100_;
  assign _113_ = calibration_age[11] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _101_;
  assign _114_ = _111_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _102_;
  assign _041_[7] = _112_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _103_;
  assign _115_ = _114_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _104_;
  assign _041_[15] = _115_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|../aimc-control-plane-rtl/aimc_control_plane.v:29|<techmap.v>:260|<techmap.v>:221" *)  _105_;
  assign _116_ = _050_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _048_[0];
  assign _117_ = _050_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  weak_tiles[4];
  assign _118_ = _050_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  weak_tiles[6];
  assign _119_ = _009_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _048_[1];
  assign _120_ = _009_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _122_;
  assign _121_ = _010_[1] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _048_[3];
  assign _009_[1] = _050_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:222" *)  weak_tiles[2];
  assign _009_[2] = _050_[5] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:222" *)  _050_[4];
  assign _009_[3] = _050_[7] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:222" *)  _050_[6];
  assign _010_[1] = _009_[3] &(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:222" *)  _009_[2];
  assign _048_[0] = weak_tiles[0] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:212" *)  _049_[0];
  assign _048_[1] = weak_tiles[1] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _116_;
  assign _122_ = weak_tiles[5] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _117_;
  assign _123_ = weak_tiles[7] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _118_;
  assign _048_[3] = weak_tiles[3] |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _119_;
  assign _124_ = _123_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _120_;
  assign _048_[7] = _124_ |(* src = "../aimc-control-plane-rtl/aimc_control_plane.v:30|<techmap.v>:260|<techmap.v>:221" *)  _121_;
  assign _019_[0] = long_context_single_decode;
  assign _023_[1] = batched_decode;
  assign _024_[1] = _019_[1];
  assign _025_[1] = _020_[1];
  assign { _030_[2], _030_[0] } = { batch_size[2], _029_[0] };
  assign { _036_[13], _036_[0] } = { active_context[13], _035_[0] };
  assign { _043_[10], _043_[0] } = { calibration_age[10], _042_[0] };
  assign { _050_[2], _050_[0] } = { weak_tiles[2], _049_[0] };
  assign _058_[0] = _057_[0];
  assign { _064_[6], _064_[0] } = { healthy_tiles[6], _063_[0] };
endmodule
