/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:1" *)
module aimc_error_budget_governor(sample_valid, analog_candidate, residual_q8, drift_age, sensitivity_q8, cumulative_error_q8, service_decision, tile_action, reason, next_cumulative_error_q8);
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [7:0] _000_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [3:0] _001_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [1:0] _002_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [1:0] _003_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [7:0] _004_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [3:0] _005_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [1:0] _006_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [1:0] _007_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [7:0] _008_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [3:0] _009_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [1:0] _010_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [7:0] _011_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [3:0] _012_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [7:0] _013_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [3:0] _014_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:37" *)
  wire [3:0] _015_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31" *)
  wire [8:0] _016_;
  wire [8:0] _017_;
  wire [8:0] _018_;
  wire [8:0] _019_;
  wire [8:0] _020_;
  wire [8:0] _021_;
  wire [8:0] _022_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [8:0] _023_;
  wire [8:0] _024_;
  wire [1:0] _025_;
  wire [3:0] _026_;
  wire [1:0] _027_;
  wire [3:0] _028_;
  wire [1:0] _029_;
  wire [3:0] _030_;
  wire [1:0] _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [3:0] _035_;
  wire [1:0] _036_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)
  wire _037_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *)
  wire _038_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *)
  wire _039_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)
  wire _040_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)
  wire _041_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:203" *)
  wire [8:0] _042_;
  wire [8:0] _043_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "8" *)
  wire [8:0] _044_;
  (* unused_bits = "0" *)
  wire [8:0] _045_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:203" *)
  wire [9:0] _046_;
  wire [9:0] _047_;
  (* src = "<techmap.v>:260" *)
  wire [8:0] _048_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _049_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _050_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _051_;
  wire [7:0] _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [3:0] _057_;
  wire [3:0] _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _063_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _064_;
  wire [7:0] _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _070_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _071_;
  wire [7:0] _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [3:0] _076_;
  wire _077_;
  wire _078_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _079_;
  wire [7:0] _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _084_;
  wire [7:0] _085_;
  wire _086_;
  wire _087_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)
  wire [8:0] _088_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _089_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _090_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _091_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _092_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _093_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _094_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _095_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _096_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _097_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _098_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _099_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)
  wire _100_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)
  wire _101_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)
  wire _102_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)
  wire _103_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _104_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _105_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _106_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)
  wire [8:0] _107_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _108_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _109_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _110_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _111_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _112_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _113_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)
  wire _114_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)
  wire _115_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)
  wire _116_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)
  wire [9:0] _117_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _118_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _119_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _120_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _121_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _122_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _123_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _124_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)
  wire _125_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)
  wire _126_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)
  wire _127_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)
  wire _128_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _129_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _130_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _131_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)
  wire _132_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _133_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _134_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)
  wire _135_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _136_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _137_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _138_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _139_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _140_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _141_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _142_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _143_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:221" *)
  wire _144_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _145_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _146_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _147_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _148_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _149_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _150_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)
  wire _151_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _152_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _153_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _154_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _155_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _156_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _157_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _158_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _159_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _160_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _161_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _162_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _163_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _164_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _165_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)
  wire _166_;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34" *)
  wire [9:0] accumulated_error;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:3" *)
  input analog_candidate;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *)
  wire [7:0] bounded_next_error;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:7" *)
  input [7:0] cumulative_error_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:5" *)
  input [3:0] drift_age;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:29" *)
  wire [8:0] drift_risk_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:11" *)
  output [7:0] next_cumulative_error_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:10" *)
  output [3:0] reason;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:4" *)
  input [7:0] residual_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:33" *)
  wire [6:0] risk_increment_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31" *)
  (* unused_bits = "0 1" *)
  wire [8:0] risk_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:2" *)
  input sample_valid;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:6" *)
  input [7:0] sensitivity_q8;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:8" *)
  output [1:0] service_decision;
  (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:9" *)
  output [1:0] tile_action;
  assign _026_[0] = _071_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  residual_q8[1];
  assign _027_[0] = _026_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _026_[1];
  assign _074_ = _027_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _027_[1];
  assign _028_[0] = _051_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _052_[1];
  assign _028_[2] = _052_[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _052_[5];
  assign _029_[0] = _028_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _028_[1];
  assign _029_[1] = _028_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _028_[3];
  assign _055_ = _029_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _029_[1];
  assign _037_ = _054_ | _055_;
  assign _030_[0] = _071_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _080_[1];
  assign _030_[1] = _080_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  residual_q8[3];
  assign _030_[2] = residual_q8[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _080_[5];
  assign _031_[0] = _030_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _030_[1];
  assign _031_[1] = _030_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _026_[3];
  assign _082_ = _031_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _031_[1];
  assign _087_ = _033_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *)  _033_[1];
  assign _034_[0] = drift_age[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *)  _058_[1];
  assign _061_ = _034_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *)  _025_[1];
  assign _038_ = _060_ | _061_;
  assign _032_[0] = _064_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _065_[1];
  assign _033_[0] = _032_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _032_[1];
  assign _068_ = _033_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _036_[1];
  assign _039_ = _067_ | _068_;
  assign _041_ = _037_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *)  _040_;
  assign _015_[0] = _038_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *)  _039_;
  assign bounded_next_error[0] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[0];
  assign bounded_next_error[1] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[1];
  assign bounded_next_error[2] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[2];
  assign bounded_next_error[3] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[3];
  assign bounded_next_error[4] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[4];
  assign bounded_next_error[5] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[5];
  assign bounded_next_error[6] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[6];
  assign bounded_next_error[7] = accumulated_error[8] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:35" *) 1'h1 : accumulated_error[7];
  assign _014_[0] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) _015_[0] : 1'h1;
  assign _013_[0] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[0] : cumulative_error_q8[0];
  assign _013_[1] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[1] : cumulative_error_q8[1];
  assign _013_[2] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[2] : cumulative_error_q8[2];
  assign _013_[3] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[3] : cumulative_error_q8[3];
  assign _013_[4] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[4] : cumulative_error_q8[4];
  assign _013_[5] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[5] : cumulative_error_q8[5];
  assign _013_[6] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[6] : cumulative_error_q8[6];
  assign _013_[7] = _014_[1] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55" *) bounded_next_error[7] : cumulative_error_q8[7];
  assign _011_[0] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[0] : _013_[0];
  assign _011_[1] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[1] : _013_[1];
  assign _011_[2] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[2] : _013_[2];
  assign _011_[3] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[3] : _013_[3];
  assign _011_[4] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[4] : _013_[4];
  assign _011_[5] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[5] : _013_[5];
  assign _011_[6] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[6] : _013_[6];
  assign _011_[7] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) cumulative_error_q8[7] : _013_[7];
  assign _012_[0] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) 1'h0 : _014_[0];
  assign _012_[1] = _041_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) 1'h0 : _014_[1];
  assign _009_[1] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _012_[1] : 1'h1;
  assign _009_[0] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _012_[0] : 1'h1;
  assign _008_[0] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[0] : cumulative_error_q8[0];
  assign _008_[1] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[1] : cumulative_error_q8[1];
  assign _008_[2] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[2] : cumulative_error_q8[2];
  assign _008_[3] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[3] : cumulative_error_q8[3];
  assign _008_[4] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[4] : cumulative_error_q8[4];
  assign _008_[5] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[5] : cumulative_error_q8[5];
  assign _008_[6] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[6] : cumulative_error_q8[6];
  assign _008_[7] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _011_[7] : cumulative_error_q8[7];
  assign _010_[0] = _009_[2] ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _012_[1] : 1'h0;
  assign _005_[1] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _009_[1] : 1'h1;
  assign _005_[2] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _009_[2] : 1'h0;
  assign _005_[0] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _009_[0] : 1'h0;
  assign _004_[0] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[0] : cumulative_error_q8[0];
  assign _004_[1] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[1] : cumulative_error_q8[1];
  assign _004_[2] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[2] : cumulative_error_q8[2];
  assign _004_[3] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[3] : cumulative_error_q8[3];
  assign _004_[4] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[4] : cumulative_error_q8[4];
  assign _004_[5] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[5] : cumulative_error_q8[5];
  assign _004_[6] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[6] : cumulative_error_q8[6];
  assign _004_[7] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _008_[7] : cumulative_error_q8[7];
  assign _006_[0] = _075_ ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _010_[0] : 1'h0;
  assign _000_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[0] : cumulative_error_q8[0];
  assign _000_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[1] : cumulative_error_q8[1];
  assign _000_[2] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[2] : cumulative_error_q8[2];
  assign _000_[3] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[3] : cumulative_error_q8[3];
  assign _000_[4] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[4] : cumulative_error_q8[4];
  assign _000_[5] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[5] : cumulative_error_q8[5];
  assign _000_[6] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[6] : cumulative_error_q8[6];
  assign _000_[7] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _004_[7] : cumulative_error_q8[7];
  assign _001_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _005_[0] : 1'h1;
  assign _001_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _005_[1] : 1'h0;
  assign _001_[2] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _005_[2] : 1'h0;
  assign _002_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _006_[0] : 1'h0;
  assign _003_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _005_[0] : 1'h0;
  assign _003_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:45" *) _007_[1] : 1'h0;
  assign tile_action[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _003_[0] : 1'h0;
  assign tile_action[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _003_[1] : 1'h0;
  assign reason[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _001_[0] : 1'h0;
  assign reason[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _001_[1] : 1'h0;
  assign reason[2] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _001_[2] : 1'h0;
  assign next_cumulative_error_q8[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[0] : cumulative_error_q8[0];
  assign next_cumulative_error_q8[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[1] : cumulative_error_q8[1];
  assign next_cumulative_error_q8[2] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[2] : cumulative_error_q8[2];
  assign next_cumulative_error_q8[3] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[3] : cumulative_error_q8[3];
  assign next_cumulative_error_q8[4] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[4] : cumulative_error_q8[4];
  assign next_cumulative_error_q8[5] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[5] : cumulative_error_q8[5];
  assign next_cumulative_error_q8[6] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[6] : cumulative_error_q8[6];
  assign next_cumulative_error_q8[7] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _000_[7] : cumulative_error_q8[7];
  assign service_decision[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:43" *) _002_[0] : 1'h0;
  assign _077_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50" *) _076_[3];
  assign _073_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _070_[7];
  assign _007_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _075_;
  assign _054_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) _056_;
  assign _053_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) _050_[7];
  assign _040_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _083_;
  assign _081_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _079_[7];
  assign _086_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47" *) _084_[7];
  assign _060_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *) _062_;
  assign _059_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58" *) _057_[3];
  assign _067_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) _069_;
  assign _066_ = ~(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53" *) _063_[7];
  assign _045_[2] = _016_[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  sensitivity_q8[6];
  assign _045_[3] = _016_[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  sensitivity_q8[7];
  assign _046_[0] = cumulative_error_q8[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[0];
  assign _117_[1] = cumulative_error_q8[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[1];
  assign _117_[2] = cumulative_error_q8[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[2];
  assign _117_[3] = cumulative_error_q8[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[3];
  assign _117_[4] = cumulative_error_q8[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[4];
  assign _117_[5] = cumulative_error_q8[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[5];
  assign _117_[6] = cumulative_error_q8[6] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260" *)  risk_increment_q8[6];
  assign accumulated_error[1] = _047_[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[0];
  assign accumulated_error[2] = _047_[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[1];
  assign accumulated_error[3] = _047_[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[2];
  assign accumulated_error[4] = _047_[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[3];
  assign accumulated_error[5] = _047_[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[4];
  assign accumulated_error[6] = _047_[6] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[5];
  assign accumulated_error[7] = cumulative_error_q8[7] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:263" *)  _046_[6];
  assign accumulated_error[0] = cumulative_error_q8[0] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[0];
  assign _047_[1] = cumulative_error_q8[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[1];
  assign _047_[2] = cumulative_error_q8[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[2];
  assign _047_[3] = cumulative_error_q8[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[3];
  assign _047_[4] = cumulative_error_q8[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[4];
  assign _047_[5] = cumulative_error_q8[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[5];
  assign _047_[6] = cumulative_error_q8[6] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:262" *)  risk_increment_q8[6];
  assign _051_[0] = sensitivity_q8[0] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _052_[1] = sensitivity_q8[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _052_[2] = sensitivity_q8[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _052_[3] = sensitivity_q8[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _052_[4] = sensitivity_q8[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _052_[5] = sensitivity_q8[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _080_[1] = residual_q8[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _080_[2] = residual_q8[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _080_[5] = residual_q8[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _072_[6] = residual_q8[6] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _072_[7] = residual_q8[7] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _064_[0] = bounded_next_error[0] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _065_[1] = bounded_next_error[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _065_[2] = bounded_next_error[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _065_[3] = bounded_next_error[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _085_[4] = bounded_next_error[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _058_[1] = drift_age[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:262" *)  1'h1;
  assign _058_[2] = drift_age[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:262" *)  1'h1;
  assign _065_[5] = bounded_next_error[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _065_[7] = bounded_next_error[7] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:262" *)  1'h1;
  assign _070_[1] = residual_q8[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _070_[0];
  assign _152_ = residual_q8[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  residual_q8[4];
  assign _153_ = _072_[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  residual_q8[6];
  assign _070_[3] = _026_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _070_[1];
  assign _154_ = _026_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _152_;
  assign _155_ = _027_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _070_[3];
  assign _026_[2] = residual_q8[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  _072_[4];
  assign _026_[3] = _072_[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  _072_[6];
  assign _027_[1] = _026_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  _026_[2];
  assign _157_ = _156_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _154_;
  assign _070_[7] = _157_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _155_;
  assign _020_[1] = drift_age[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50|<techmap.v>:260|<techmap.v>:221" *)  drift_age[0];
  assign _078_ = _025_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50|<techmap.v>:260|<techmap.v>:221" *)  _020_[1];
  assign _076_[3] = _020_[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50|<techmap.v>:260|<techmap.v>:221" *)  _078_;
  assign _089_ = _043_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _042_[0];
  assign _090_ = _043_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _088_[2];
  assign _091_ = _043_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _088_[4];
  assign _092_ = residual_q8[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _088_[6];
  assign _093_ = _096_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _042_[1];
  assign _094_ = _098_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _105_;
  assign _095_ = _099_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _042_[3];
  assign _096_ = _043_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _043_[2];
  assign _097_ = _043_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _043_[4];
  assign _098_ = residual_q8[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _043_[6];
  assign _099_ = _098_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _097_;
  assign _100_ = _097_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _042_[3];
  assign _101_ = _043_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _042_[1];
  assign _102_ = _043_[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _042_[3];
  assign _103_ = _043_[6] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _042_[5];
  assign _042_[1] = _088_[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _089_;
  assign _104_ = _088_[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _090_;
  assign _105_ = _088_[5] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _091_;
  assign _042_[3] = _104_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _093_;
  assign _106_ = _092_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _094_;
  assign _016_[8] = _106_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _095_;
  assign _042_[5] = _105_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _100_;
  assign _042_[2] = _088_[2] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _101_;
  assign _042_[4] = _088_[4] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _102_;
  assign _042_[6] = _088_[6] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _103_;
  assign _108_ = _045_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _044_[0];
  assign _109_ = _045_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _107_[2];
  assign _110_ = _111_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _044_[1];
  assign _044_[7] = _114_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _044_[3];
  assign _111_ = _045_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _045_[2];
  assign _112_ = _016_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _016_[4];
  assign _113_ = _016_[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _016_[6];
  assign _114_ = _113_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:222" *)  _112_;
  assign _044_[5] = _112_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _044_[3];
  assign _115_ = _045_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _044_[1];
  assign _044_[4] = _016_[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _044_[3];
  assign _044_[6] = _016_[6] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _044_[5];
  assign _044_[1] = _107_[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _108_;
  assign _116_ = _107_[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _109_;
  assign _044_[3] = _116_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:221" *)  _110_;
  assign _044_[2] = _107_[2] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260|<techmap.v>:229" *)  _115_;
  assign _118_ = _047_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _046_[0];
  assign _119_ = _047_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _117_[2];
  assign _120_ = _047_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _117_[4];
  assign _121_ = cumulative_error_q8[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _117_[6];
  assign _122_ = _125_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _046_[1];
  assign _123_ = _127_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _134_;
  assign _124_ = _128_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _046_[3];
  assign _125_ = _047_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)  _047_[2];
  assign _126_ = _047_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)  _047_[4];
  assign _127_ = cumulative_error_q8[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)  _047_[6];
  assign _128_ = _127_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:222" *)  _126_;
  assign _129_ = _126_ &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _046_[3];
  assign _130_ = _047_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _046_[1];
  assign _131_ = _047_[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _046_[3];
  assign _132_ = _047_[6] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _046_[5];
  assign _046_[1] = _117_[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _118_;
  assign _133_ = _117_[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _119_;
  assign _134_ = _117_[5] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _120_;
  assign _046_[3] = _133_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _122_;
  assign _135_ = _121_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _123_;
  assign accumulated_error[8] = _135_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:221" *)  _124_;
  assign _046_[5] = _134_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _129_;
  assign _046_[2] = _117_[2] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _130_;
  assign _046_[4] = _117_[4] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _131_;
  assign _046_[6] = _117_[6] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:34|<techmap.v>:260|<techmap.v>:229" *)  _132_;
  assign _136_ = _052_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _050_[0];
  assign _137_ = _052_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  sensitivity_q8[2];
  assign _138_ = _052_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  sensitivity_q8[4];
  assign _139_ = _028_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _050_[1];
  assign _140_ = _028_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _143_;
  assign _141_ = _029_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _050_[3];
  assign _028_[1] = _052_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:222" *)  _052_[2];
  assign _028_[3] = sensitivity_q8[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:222" *)  sensitivity_q8[6];
  assign _050_[0] = sensitivity_q8[0] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:212" *)  _051_[0];
  assign _050_[1] = sensitivity_q8[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _136_;
  assign _142_ = sensitivity_q8[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _137_;
  assign _143_ = sensitivity_q8[5] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _138_;
  assign _050_[3] = _142_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _139_;
  assign _050_[7] = _140_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _141_;
  assign _017_[2] = drift_age[2] ^(* src = "<techmap.v>:190" *)  drift_age[1];
  assign _017_[3] = drift_age[3] ^(* src = "<techmap.v>:190" *)  drift_age[2];
  assign _020_[2] = drift_age[1] &(* src = "<techmap.v>:189" *)  drift_age[2];
  assign _021_[2] = _017_[2] &(* src = "<techmap.v>:189" *)  _020_[1];
  assign _021_[3] = _017_[3] &(* src = "<techmap.v>:189" *)  _020_[2];
  assign _019_[5] = drift_age[3] &(* src = "<techmap.v>:189" *)  _020_[3];
  assign drift_risk_q8[2] = _017_[2] ^(* src = "<techmap.v>:189" *)  _020_[1];
  assign _018_[3] = _017_[3] ^(* src = "<techmap.v>:189" *)  _020_[2];
  assign _018_[4] = drift_age[3] ^(* src = "<techmap.v>:189" *)  _020_[3];
  assign _022_[3] = _018_[3] &(* src = "<techmap.v>:189" *)  _021_[2];
  assign _022_[4] = _018_[4] &(* src = "<techmap.v>:189" *)  _021_[3];
  assign drift_risk_q8[3] = _018_[3] ^(* src = "<techmap.v>:189" *)  _021_[2];
  assign _019_[4] = _018_[4] ^(* src = "<techmap.v>:189" *)  _021_[3];
  assign _023_[4] = _019_[4] &(* src = "<techmap.v>:260" *)  _022_[3];
  assign _048_[5] = _019_[5] &(* src = "<techmap.v>:260" *)  _022_[4];
  assign drift_risk_q8[4] = _019_[4] ^(* src = "<techmap.v>:262" *)  _022_[3];
  assign _024_[5] = _019_[5] ^(* src = "<techmap.v>:262" *)  _022_[4];
  assign drift_risk_q8[5] = _024_[5] ^(* src = "<techmap.v>:263" *)  _023_[4];
  assign _158_ = _080_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _070_[0];
  assign _026_[1] = residual_q8[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  residual_q8[2];
  assign _159_ = _030_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _079_[1];
  assign _160_ = _026_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  residual_q8[5];
  assign _161_ = _031_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _079_[3];
  assign _070_[0] = residual_q8[0] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:212" *)  _071_[0];
  assign _079_[1] = residual_q8[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _158_;
  assign _156_ = residual_q8[7] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _153_;
  assign _079_[3] = _026_[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _159_;
  assign _162_ = _156_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _160_;
  assign _079_[7] = _162_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _161_;
  assign _145_ = _065_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _063_[0];
  assign _146_ = _065_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  bounded_next_error[2];
  assign _163_ = bounded_next_error[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  bounded_next_error[4];
  assign _164_ = _032_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _163_;
  assign _165_ = _033_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _063_[3];
  assign _032_[1] = _065_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  _065_[2];
  assign _032_[2] = bounded_next_error[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  _085_[4];
  assign _032_[3] = _065_[7] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  bounded_next_error[6];
  assign _033_[1] = _032_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:222" *)  _032_[2];
  assign _166_ = bounded_next_error[7] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _164_;
  assign _084_[7] = _166_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:55|../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:260|<techmap.v>:221" *)  _165_;
  assign _020_[3] = drift_age[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:221" *)  drift_age[2];
  assign _144_ = _025_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:221" *)  _057_[1];
  assign _025_[1] = drift_age[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:222" *)  _058_[2];
  assign _057_[1] = drift_age[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:221" *)  _034_[0];
  assign _057_[3] = _020_[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|<techmap.v>:260|<techmap.v>:221" *)  _144_;
  assign _147_ = _032_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _063_[1];
  assign _148_ = _032_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  bounded_next_error[5];
  assign _149_ = _036_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _063_[3];
  assign _035_[2] = _065_[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:222" *)  bounded_next_error[4];
  assign _036_[1] = _032_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:222" *)  _035_[2];
  assign _063_[0] = bounded_next_error[0] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:212" *)  _064_[0];
  assign _063_[1] = bounded_next_error[1] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _145_;
  assign _150_ = bounded_next_error[3] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _146_;
  assign _063_[3] = _150_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _147_;
  assign _151_ = bounded_next_error[7] |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _148_;
  assign _063_[7] = _151_ |(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:58|../aimc-control-plane-rtl/aimc_error_budget_governor.v:53|<techmap.v>:260|<techmap.v>:221" *)  _149_;
  assign _049_ = _024_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _023_[4];
  assign drift_risk_q8[6] = _048_[5] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _049_;
  assign _075_ = _073_ | _074_;
  assign _056_ = _053_ | _055_;
  assign _083_ = _081_ | _082_;
  assign _014_[1] = _086_ | _087_;
  assign _009_[2] = _077_ | _078_;
  assign _062_ = _059_ | _061_;
  assign _069_ = _066_ | _068_;
  assign _071_[0] = residual_q8[0] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign _072_[4] = residual_q8[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:47|<techmap.v>:262" *)  1'h1;
  assign drift_risk_q8[1] = drift_age[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:50|<techmap.v>:263" *)  drift_age[0];
  assign _042_[0] = residual_q8[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_age[0];
  assign _088_[1] = residual_q8[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_risk_q8[1];
  assign _088_[2] = residual_q8[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_risk_q8[2];
  assign _088_[3] = residual_q8[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_risk_q8[3];
  assign _088_[4] = residual_q8[4] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_risk_q8[4];
  assign _088_[5] = residual_q8[5] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_risk_q8[5];
  assign _088_[6] = residual_q8[6] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  drift_risk_q8[6];
  assign _016_[1] = _043_[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[0];
  assign _016_[2] = _043_[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[1];
  assign _016_[3] = _043_[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[2];
  assign _016_[4] = _043_[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[3];
  assign _016_[5] = _043_[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[4];
  assign _016_[6] = _043_[6] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[5];
  assign _016_[7] = residual_q8[7] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _042_[6];
  assign _016_[0] = residual_q8[0] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_age[0];
  assign _043_[1] = residual_q8[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_risk_q8[1];
  assign _043_[2] = residual_q8[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_risk_q8[2];
  assign _043_[3] = residual_q8[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_risk_q8[3];
  assign _043_[4] = residual_q8[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_risk_q8[4];
  assign _043_[5] = residual_q8[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_risk_q8[5];
  assign _043_[6] = residual_q8[6] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  drift_risk_q8[6];
  assign _044_[0] = _016_[0] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  sensitivity_q8[4];
  assign _107_[1] = _016_[1] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  sensitivity_q8[5];
  assign _107_[2] = _016_[2] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  sensitivity_q8[6];
  assign _107_[3] = _016_[3] &(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:260" *)  sensitivity_q8[7];
  assign risk_increment_q8[0] = _045_[2] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[1];
  assign risk_increment_q8[1] = _045_[3] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[2];
  assign risk_increment_q8[2] = _016_[4] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[3];
  assign risk_increment_q8[3] = _016_[5] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[4];
  assign risk_increment_q8[4] = _016_[6] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[5];
  assign risk_increment_q8[5] = _016_[7] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[6];
  assign risk_increment_q8[6] = _016_[8] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:263" *)  _044_[7];
  assign _045_[1] = _016_[1] ^(* src = "../aimc-control-plane-rtl/aimc_error_budget_governor.v:31|<techmap.v>:262" *)  sensitivity_q8[5];
  assign _001_[3] = 1'h0;
  assign _002_[1] = 1'h0;
  assign _005_[3] = 1'h0;
  assign _006_[1] = 1'h0;
  assign _007_[0] = _005_[0];
  assign _009_[3] = 1'h0;
  assign _010_[1] = 1'h0;
  assign _012_[3:2] = 2'h1;
  assign _014_[3:2] = 2'h1;
  assign _015_[3:1] = 3'h3;
  assign { _017_[8:4], _017_[1:0] } = { 4'h0, drift_age[3], drift_risk_q8[1], drift_age[0] };
  assign { _018_[8:5], _018_[2:0] } = { 4'h0, drift_risk_q8[2:1], drift_age[0] };
  assign { _019_[8:6], _019_[3:0] } = { 3'h0, drift_risk_q8[3:1], drift_age[0] };
  assign { _020_[8:4], _020_[0] } = 6'h00;
  assign { _021_[8:4], _021_[1:0] } = { 4'h0, _019_[5], 2'h0 };
  assign { _022_[8:5], _022_[2:0] } = 7'h00;
  assign { _023_[8:5], _023_[3:0] } = { 3'h0, drift_risk_q8[6], 4'h0 };
  assign { _024_[8:6], _024_[4:0] } = { 3'h0, drift_risk_q8[4:1], drift_age[0] };
  assign _025_[0] = _020_[1];
  assign _030_[3] = _026_[3];
  assign _034_[1] = _025_[1];
  assign { _035_[3], _035_[1:0] } = { _032_[3], _032_[1:0] };
  assign _036_[0] = _033_[0];
  assign _042_[8:7] = { 1'h0, _016_[8] };
  assign { _043_[8:7], _043_[0] } = { 1'h0, residual_q8[7], _016_[0] };
  assign { _045_[8:4], _045_[0] } = { _016_[8:4], risk_q8[0] };
  assign _046_[9:7] = { 2'h0, accumulated_error[8] };
  assign { _047_[9:7], _047_[0] } = { 2'h0, cumulative_error_q8[7], accumulated_error[0] };
  assign { _048_[8:6], _048_[4:0] } = { 3'h0, _023_[4], 4'h0 };
  assign { _052_[7:6], _052_[0] } = { sensitivity_q8[7:6], _051_[0] };
  assign _057_[0] = drift_age[0];
  assign { _058_[3], _058_[0] } = { drift_age[3], drift_age[0] };
  assign { _065_[6], _065_[4], _065_[0] } = { bounded_next_error[6], bounded_next_error[4], _064_[0] };
  assign { _072_[5], _072_[3:0] } = { residual_q8[5], residual_q8[3:1], _071_[0] };
  assign _076_[1:0] = { _020_[1], drift_age[0] };
  assign _079_[0] = _070_[0];
  assign { _080_[7:6], _080_[4:3], _080_[0] } = { _072_[7:6], residual_q8[4:3], _071_[0] };
  assign _084_[3:0] = _063_[3:0];
  assign { _085_[7:5], _085_[3:0] } = { _065_[7], bounded_next_error[6:5], _065_[3:1], _064_[0] };
  assign { _088_[8:7], _088_[0] } = { 2'h0, _042_[0] };
  assign { _107_[8:4], _107_[0] } = { 5'h00, _044_[0] };
  assign { _117_[9:7], _117_[0] } = { 3'h0, _046_[0] };
  assign accumulated_error[9] = 1'h0;
  assign { drift_risk_q8[8:7], drift_risk_q8[0] } = { 2'h0, drift_age[0] };
  assign reason[3] = 1'h0;
  assign risk_q8[8:2] = risk_increment_q8;
  assign service_decision[1] = 1'h0;
endmodule
