/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:1" *)
module aimc_tile_service_scheduler(sample_valid, analog_candidate, requested_tile_id, tile0_health_action, tile1_health_action, tile2_health_action, tile3_health_action, tile_busy, maintenance_budget, service_decision, selected_tile, reason);
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [3:0] _000_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _001_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _002_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _003_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire _004_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [3:0] _005_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _006_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _007_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [3:0] _008_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _009_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _010_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [3:0] _011_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _012_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _013_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [3:0] _014_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _015_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _016_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [3:0] _017_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:88" *)
  wire [1:0] _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire [1:0] _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [1:0] _035_;
  wire [1:0] _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire [1:0] _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:36" *)
  wire _050_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:36" *)
  wire _051_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:37" *)
  wire _052_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:37" *)
  wire _053_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:38" *)
  wire _054_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:38" *)
  wire _055_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:39" *)
  wire _056_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:39" *)
  wire _057_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:40" *)
  wire _058_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:41" *)
  wire _059_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:42" *)
  wire _060_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:43" *)
  wire _061_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *)
  wire _062_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *)
  wire _063_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *)
  wire _064_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *)
  wire _065_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *)
  wire _066_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *)
  wire _067_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *)
  wire _068_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:48" *)
  wire _069_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:48" *)
  wire _070_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:49" *)
  wire _071_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:49" *)
  wire _072_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:50" *)
  wire _073_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:50" *)
  wire _074_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:432" *)
  wire [5:0] _075_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:428" *)
  wire [1:0] _076_;
  wire [1:0] _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [1:0] _081_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:432" *)
  wire [2:0] _082_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:428" *)
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:445" *)
  wire _086_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *)
  wire [1:0] _087_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *)
  wire [1:0] _088_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *)
  wire [1:0] _089_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *)
  wire [1:0] _090_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *)
  wire [1:0] _091_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *)
  wire [1:0] _092_;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:3" *)
  input analog_candidate;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:50" *)
  wire any_probe_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:49" *)
  wire any_recalibrate_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:48" *)
  wire any_serving_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:59" *)
  wire [1:0] first_probe_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:55" *)
  wire [1:0] first_recalibrate_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:51" *)
  wire [1:0] first_serving_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:12" *)
  input [1:0] maintenance_budget;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:15" *)
  output [3:0] reason;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:35" *)
  wire [1:0] requested_index;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:5" *)
  input [7:0] requested_tile_id;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:2" *)
  input sample_valid;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:14" *)
  output [1:0] selected_tile;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:13" *)
  output [1:0] service_decision;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:36" *)
  wire tile0_can_serve;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:7" *)
  input [1:0] tile0_health_action;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *)
  wire tile0_needs_probe;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:40" *)
  wire tile0_needs_recalibrate;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:37" *)
  wire tile1_can_serve;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:8" *)
  input [1:0] tile1_health_action;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *)
  wire tile1_needs_probe;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:41" *)
  wire tile1_needs_recalibrate;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:38" *)
  wire tile2_can_serve;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:9" *)
  input [1:0] tile2_health_action;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *)
  wire tile2_needs_probe;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:42" *)
  wire tile2_needs_recalibrate;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:39" *)
  wire tile3_can_serve;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:10" *)
  input [1:0] tile3_health_action;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *)
  wire tile3_needs_probe;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:43" *)
  wire tile3_needs_recalibrate;
  (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:11" *)
  input [3:0] tile_busy;
  assign _040_ = _030_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:40" *)  tile0_health_action[1];
  assign _041_ = _031_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:41" *)  tile1_health_action[1];
  assign _042_ = _032_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:42" *)  tile2_health_action[1];
  assign _043_ = _033_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:43" *)  tile3_health_action[1];
  assign _044_ = _030_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *)  _034_[1];
  assign _045_ = _031_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *)  _035_[1];
  assign _046_ = _032_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *)  _036_[1];
  assign _047_ = _033_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *)  _037_[1];
  assign _048_ = requested_tile_id[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *)  _038_[1];
  assign _049_ = _039_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:81|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *)  requested_tile_id[1];
  assign _086_ = _019_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:445" *)  _080_;
  assign _020_ = _075_[1] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:441" *)  _075_[3];
  assign _076_[1] = _020_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:441" *)  _075_[5];
  assign _021_ = _075_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:441" *)  _075_[2];
  assign _076_[0] = _021_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:441" *)  _075_[4];
  assign _022_ = _082_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:441" *)  _082_[1];
  assign _083_ = _022_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:441" *)  _082_[2];
  assign _019_ = _078_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:445" *)  _079_;
  assign _023_ = tile0_health_action[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:36" *)  tile0_health_action[1];
  assign _024_ = tile1_health_action[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:37" *)  tile1_health_action[1];
  assign _025_ = tile2_health_action[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:38" *)  tile2_health_action[1];
  assign _026_ = tile3_health_action[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:39" *)  tile3_health_action[1];
  assign _027_ = _003_[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *)  _003_[1];
  assign _028_ = maintenance_budget[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *)  maintenance_budget[1];
  assign _029_ = requested_tile_id[0] |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:80|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *)  requested_tile_id[1];
  assign _051_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:36" *) _023_;
  assign _053_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:37" *) _024_;
  assign _054_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:38" *) _025_;
  assign _057_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:39" *) _026_;
  assign _058_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:40" *) _040_;
  assign _059_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:41" *) _041_;
  assign _060_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:42" *) _042_;
  assign _061_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:43" *) _043_;
  assign _062_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *) _044_;
  assign _063_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *) _045_;
  assign _064_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *) _046_;
  assign _065_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *) _047_;
  assign _067_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) _027_;
  assign _078_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *) _048_;
  assign _079_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:81|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *) _049_;
  assign _080_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:80|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *) _029_;
  assign tile0_can_serve = _050_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:36" *)  _051_;
  assign tile3_can_serve = _056_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:39" *)  _057_;
  assign tile1_can_serve = _052_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:37" *)  _053_;
  assign tile2_can_serve = _055_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:38" *)  _054_;
  assign tile2_needs_recalibrate = _055_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:42" *)  _060_;
  assign tile0_needs_recalibrate = _050_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:40" *)  _058_;
  assign tile1_needs_recalibrate = _052_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:41" *)  _059_;
  assign tile1_needs_probe = _052_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *)  _063_;
  assign tile3_needs_recalibrate = _056_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:43" *)  _061_;
  assign tile0_needs_probe = _050_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *)  _062_;
  assign tile2_needs_probe = _055_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *)  _064_;
  assign tile3_needs_probe = _056_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *)  _065_;
  assign _069_ = tile0_can_serve |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:48" *)  tile1_can_serve;
  assign _070_ = _069_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:48" *)  tile2_can_serve;
  assign any_serving_tile = _070_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:48" *)  tile3_can_serve;
  assign _071_ = tile0_needs_recalibrate |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:49" *)  tile1_needs_recalibrate;
  assign _072_ = _071_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:49" *)  tile2_needs_recalibrate;
  assign any_recalibrate_tile = _072_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:49" *)  tile3_needs_recalibrate;
  assign _073_ = tile0_needs_probe |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:50" *)  tile1_needs_probe;
  assign _074_ = _073_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:50" *)  tile2_needs_probe;
  assign any_probe_tile = _074_ |(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:50" *)  tile3_needs_probe;
  assign _068_ = _066_ &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *)  _067_;
  assign _087_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *) tile2_can_serve;
  assign _088_[0] = tile1_can_serve ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *) 1'h1 : _087_[0];
  assign _088_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *) tile1_can_serve;
  assign first_serving_tile[0] = tile0_can_serve ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *) 1'h0 : _088_[0];
  assign first_serving_tile[1] = tile0_can_serve ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:54" *) 1'h0 : _088_[1];
  assign _092_[0] = tile1_needs_probe ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *) 1'h1 : _091_[0];
  assign _092_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *) tile1_needs_probe;
  assign _089_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *) tile2_needs_recalibrate;
  assign _090_[0] = tile1_needs_recalibrate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *) 1'h1 : _089_[0];
  assign _090_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *) tile1_needs_recalibrate;
  assign first_recalibrate_tile[0] = tile0_needs_recalibrate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *) 1'h0 : _090_[0];
  assign first_recalibrate_tile[1] = tile0_needs_recalibrate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:58" *) 1'h0 : _090_[1];
  assign _091_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *) tile2_needs_probe;
  assign first_probe_tile[0] = tile0_needs_probe ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *) 1'h0 : _092_[0];
  assign first_probe_tile[1] = tile0_needs_probe ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:62" *) 1'h0 : _092_[1];
  assign _017_[1] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:114" *) any_probe_tile;
  assign _018_[0] = any_probe_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:114" *) first_probe_tile[0] : requested_tile_id[0];
  assign _018_[1] = any_probe_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:114" *) first_probe_tile[1] : requested_tile_id[1];
  assign _014_[0] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:110" *) any_recalibrate_tile;
  assign _014_[1] = any_recalibrate_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:110" *) 1'h0 : _017_[1];
  assign _015_[0] = any_recalibrate_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:110" *) first_recalibrate_tile[0] : _018_[0];
  assign _015_[1] = any_recalibrate_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:110" *) first_recalibrate_tile[1] : _018_[1];
  assign _016_[0] = any_recalibrate_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:110" *) 1'h0 : any_probe_tile;
  assign _016_[1] = any_recalibrate_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:110" *) 1'h1 : any_probe_tile;
  assign _011_[0] = _028_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *) _014_[0] : 1'h0;
  assign _011_[1] = _028_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *) _014_[1] : 1'h1;
  assign _013_[0] = _028_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *) _016_[0] : 1'h0;
  assign _013_[1] = _028_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *) _016_[1] : 1'h0;
  assign _012_[0] = _028_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *) _015_[0] : requested_tile_id[0];
  assign _012_[1] = _028_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:107" *) _015_[1] : requested_tile_id[1];
  assign _008_[0] = any_serving_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) 1'h1 : _011_[0];
  assign _008_[1] = any_serving_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) 1'h1 : _011_[1];
  assign _008_[2] = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) any_serving_tile;
  assign _009_[0] = any_serving_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) first_serving_tile[0] : _012_[0];
  assign _009_[1] = any_serving_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) first_serving_tile[1] : _012_[1];
  assign _010_[0] = any_serving_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) 1'h1 : _013_[0];
  assign _010_[1] = any_serving_tile ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:103" *) 1'h0 : _013_[1];
  assign _005_[0] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) 1'h0 : _008_[0];
  assign _005_[1] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) 1'h1 : _008_[1];
  assign _005_[2] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) 1'h0 : _008_[2];
  assign _006_[0] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) requested_tile_id[0] : _009_[0];
  assign _006_[1] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) requested_tile_id[1] : _009_[1];
  assign _007_[0] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) 1'h1 : _010_[0];
  assign _007_[1] = _068_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) 1'h0 : _010_[1];
  assign _081_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _077_[0] : 1'hx;
  assign _081_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _077_[1] : 1'hx;
  assign _003_[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _081_[0] : 1'hx;
  assign _003_[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _081_[1] : 1'hx;
  assign _085_ = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _084_ : 1'hx;
  assign _004_ = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _085_ : 1'hx;
  assign _002_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _007_[0] : 1'h0;
  assign _002_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _007_[1] : 1'h0;
  assign _000_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _005_[0] : 1'h1;
  assign _000_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _005_[1] : 1'h0;
  assign _000_[2] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _005_[2] : 1'h0;
  assign reason[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _000_[0] : 1'h0;
  assign reason[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _000_[1] : 1'h0;
  assign reason[2] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _000_[2] : 1'h0;
  assign _001_[0] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _006_[0] : requested_tile_id[0];
  assign _001_[1] = analog_candidate ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:96" *) _006_[1] : requested_tile_id[1];
  assign service_decision[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _002_[0] : 1'h0;
  assign service_decision[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _002_[1] : 1'h0;
  assign selected_tile[0] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _001_[0] : requested_tile_id[0];
  assign selected_tile[1] = sample_valid ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:93" *) _001_[1] : requested_tile_id[1];
  assign _077_[0] = _086_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:445" *) _076_[0] : tile3_health_action[0];
  assign _077_[1] = _086_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:445" *) _076_[1] : tile3_health_action[1];
  assign _084_ = _086_ ? (* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:445" *) _083_ : tile_busy[3];
  assign _050_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *) tile_busy[0];
  assign _052_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *) tile_busy[1];
  assign _055_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *) tile_busy[2];
  assign _056_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *) tile_busy[3];
  assign _066_ = ~(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:99" *) _004_;
  assign _030_[0] = tile0_health_action[0] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *)  1'h1;
  assign _034_[1] = tile0_health_action[1] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:44" *)  1'h1;
  assign _031_[0] = tile1_health_action[0] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *)  1'h1;
  assign _035_[1] = tile1_health_action[1] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:45" *)  1'h1;
  assign _032_[0] = tile2_health_action[0] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *)  1'h1;
  assign _036_[1] = tile2_health_action[1] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:46" *)  1'h1;
  assign _033_[0] = tile3_health_action[0] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *)  1'h1;
  assign _037_[1] = tile3_health_action[1] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:47" *)  1'h1;
  assign _038_[1] = requested_tile_id[1] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *)  1'h1;
  assign _039_[0] = requested_tile_id[0] ^(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:81|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79" *)  1'h1;
  assign _075_[4] = tile0_health_action[0] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:434" *)  _080_;
  assign _075_[5] = tile0_health_action[1] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:434" *)  _080_;
  assign _075_[0] = tile2_health_action[0] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:434" *)  _078_;
  assign _075_[1] = tile2_health_action[1] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:434" *)  _078_;
  assign _075_[2] = tile1_health_action[0] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:434" *)  _079_;
  assign _075_[3] = tile1_health_action[1] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:70|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:67|<techmap.v>:434" *)  _079_;
  assign _082_[1] = tile_busy[1] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:434" *)  _079_;
  assign _082_[2] = tile_busy[0] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:434" *)  _080_;
  assign _082_[0] = tile_busy[2] &(* src = "../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:82|../aimc-control-plane-rtl/aimc_tile_service_scheduler.v:79|<techmap.v>:434" *)  _078_;
  assign _000_[3] = 1'h0;
  assign _005_[3] = 1'h0;
  assign _008_[3] = 1'h0;
  assign _011_[3:2] = 2'h1;
  assign _014_[3:2] = 2'h1;
  assign { _017_[3:2], _017_[0] } = 3'h3;
  assign _030_[1] = tile0_health_action[1];
  assign _031_[1] = tile1_health_action[1];
  assign _032_[1] = tile2_health_action[1];
  assign _033_[1] = tile3_health_action[1];
  assign _034_[0] = _030_[0];
  assign _035_[0] = _031_[0];
  assign _036_[0] = _032_[0];
  assign _037_[0] = _033_[0];
  assign _038_[0] = requested_tile_id[0];
  assign _039_[1] = requested_tile_id[1];
  assign _087_[1] = 1'h1;
  assign _089_[1] = 1'h1;
  assign _091_[1] = 1'h1;
  assign reason[3] = 1'h0;
  assign requested_index = requested_tile_id[1:0];
endmodule
