"""Deterministic generation of reviewable SVA source from approved plans."""

from __future__ import annotations

from pathlib import Path

from .planner import CheckPlan


def generate_sva_module(plans: list[CheckPlan], *, module_name: str = "generated_checks", dut_name: str = "dut") -> str:
    if not module_name.isidentifier() or not dut_name.isidentifier():
        raise ValueError("module and DUT names must be identifiers")
    lines = [f"// Generated by verification_platform; {len(plans)} approved plans", f"module {module_name} (input logic clk, input logic rst, input logic enable, input logic [3:0] counter_q);"]
    for plan in plans:
        lines.extend([f"  // requirement: {plan.requirement_id}", f"  // rationale: {plan.rationale}", f"  {plan.assertion}"])
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def write_sva_module(plans: list[CheckPlan], path: str | Path, *, module_name: str = "generated_checks", dut_name: str = "dut") -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_sva_module(plans, module_name=module_name, dut_name=dut_name), encoding="utf-8")
    return output
