#!/usr/bin/env python3
"""Verify runtime matrix gates and local profile evidence."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "runtime-matrix" / "matrix.json"
SITE_PAGE = ROOT / "site" / "runtime-matrix.html"
REQUIRED_PROFILES = {"cpu-local", "cuda-dev", "triton-dev", "rocm-hip-dev", "compiler-runtime-inspection-dev", "tensor-core-gemm-dev", "persistent-kernels-dev", "parallel-primitives-dev", "custom-op-dev", "autotune-dev", "model-integration-dev", "serving-dev", "kv-cache-paged-attention-dev", "attention-serving-stack-dev", "flash-attention-backward-dev", "sparse-attention-kernels-dev", "fused-training-kernels-dev", "serving-engine-comparison-dev", "speculative-decoding-serving-dev", "distributed-topology-dev", "distributed-collectives-dev", "distributed-training-optimizer-dev", "moe-routing-all-to-all-dev", "hardware-capacity-dev", "quantization-memory-dev", "numerical-reproducibility-dev", "cuda-graphs-latency-dev", "multi-tenant-scheduling-dev", "regression-ledger-dev", "gpu-promotion-dev", "gpu-promotion-suite-dev", "gpu-import-lint-dev", "gpu-runs-dev", "gpu-provenance-dev", "gpu-measurement-queue-dev", "gpu-acceptance-logic-dev", "gpu-host-preflight-dev", "gpu-handoff-dev", "assessment-dev", "assessment-grading-dev", "capstone-acceptance-dev", "profiler-dev", "distributed-dev"}


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> int:
    if not MATRIX.exists():
        subprocess.run([sys.executable, "scripts/build_runtime_matrix.py"], cwd=ROOT, check=True)
    matrix = load_json(MATRIX)
    profiles = matrix.get("profiles", [])
    profile_ids = {row.get("id") for row in profiles}
    require(REQUIRED_PROFILES.issubset(profile_ids), f"missing runtime profiles: {sorted(REQUIRED_PROFILES - profile_ids)}")
    require(matrix.get("profile_count") == len(profiles), "runtime profile count mismatch")
    require(matrix.get("local_capabilities", {}).get("python") is True, "python capability must be true")
    cpu = next(row for row in profiles if row["id"] == "cpu-local")
    require(cpu["status"] == "ready", "cpu-local profile should be ready on this machine")
    require(cpu.get("local_facts", {}).get("kernel_benchmarks", 0) >= 14, "cpu-local lacks kernel benchmark evidence")
    serving = next(row for row in profiles if row["id"] == "serving-dev")
    require(serving["status"] == "ready", "serving-dev profile should be ready on this machine")
    require(serving.get("local_facts", {}).get("passed_traces", 0) >= 3, "serving-dev lacks trace replay evidence")
    kv_cache = next(row for row in profiles if row["id"] == "kv-cache-paged-attention-dev")
    require(kv_cache["status"] == "ready", "kv-cache-paged-attention-dev profile should be ready on this machine")
    require(kv_cache.get("local_facts", {}).get("status") == "kv-cache-ready", "kv-cache-paged-attention-dev did not complete")
    require(kv_cache.get("local_facts", {}).get("scenarios", 0) >= 5, "kv-cache-paged-attention-dev lacks scenarios")
    require(kv_cache.get("local_facts", {}).get("prefix_blocks_reused", 0) > 0, "kv-cache-paged-attention-dev lacks prefix reuse evidence")
    attention_serving = next(row for row in profiles if row["id"] == "attention-serving-stack-dev")
    require(attention_serving["status"] == "ready", "attention-serving-stack-dev profile should be ready on this machine")
    require(attention_serving.get("local_facts", {}).get("status") == "attention-serving-ready", "attention-serving-stack-dev did not complete")
    require(attention_serving.get("local_facts", {}).get("scenarios", 0) >= 5, "attention-serving-stack-dev lacks scenarios")
    require(attention_serving.get("local_facts", {}).get("prefix_blocks_reused", 0) > 0, "attention-serving-stack-dev lacks prefix reuse evidence")
    flash_backward = next(row for row in profiles if row["id"] == "flash-attention-backward-dev")
    require(flash_backward["status"] == "ready", "flash-attention-backward-dev profile should be ready on this machine")
    require(flash_backward.get("local_facts", {}).get("status") == "flash-attention-backward-ready", "flash-attention-backward-dev did not complete")
    require(flash_backward.get("local_facts", {}).get("scenarios", 0) >= 6, "flash-attention-backward-dev lacks scenarios")
    require(flash_backward.get("local_facts", {}).get("dropout", 0) >= 1, "flash-attention-backward-dev lacks dropout coverage")
    sparse_attention = next(row for row in profiles if row["id"] == "sparse-attention-kernels-dev")
    require(sparse_attention["status"] == "ready", "sparse-attention-kernels-dev profile should be ready on this machine")
    require(sparse_attention.get("local_facts", {}).get("status") == "sparse-attention-ready", "sparse-attention-kernels-dev did not complete")
    require(sparse_attention.get("local_facts", {}).get("scenarios", 0) >= 6, "sparse-attention-kernels-dev lacks scenarios")
    require(sparse_attention.get("local_facts", {}).get("patterns", 0) >= 6, "sparse-attention-kernels-dev lacks pattern coverage")
    require(sparse_attention.get("local_facts", {}).get("ragged", 0) >= 1, "sparse-attention-kernels-dev lacks ragged coverage")
    fused_training = next(row for row in profiles if row["id"] == "fused-training-kernels-dev")
    require(fused_training["status"] == "ready", "fused-training-kernels-dev profile should be ready on this machine")
    require(fused_training.get("local_facts", {}).get("status") == "fused-training-ready", "fused-training-kernels-dev did not complete")
    require(fused_training.get("local_facts", {}).get("scenarios", 0) >= 6, "fused-training-kernels-dev lacks scenarios")
    require(fused_training.get("local_facts", {}).get("families", 0) >= 5, "fused-training-kernels-dev lacks family coverage")
    require(fused_training.get("local_facts", {}).get("optimizer_state", 0) >= 2, "fused-training-kernels-dev lacks optimizer-state coverage")
    speculative = next(row for row in profiles if row["id"] == "speculative-decoding-serving-dev")
    require(speculative["status"] == "ready", "speculative-decoding-serving-dev profile should be ready on this machine")
    require(speculative.get("local_facts", {}).get("status") == "speculative-decoding-ready", "speculative-decoding-serving-dev did not complete")
    require(speculative.get("local_facts", {}).get("scenarios", 0) >= 6, "speculative-decoding-serving-dev lacks scenarios")
    require(speculative.get("local_facts", {}).get("engines", 0) >= 4, "speculative-decoding-serving-dev lacks engine coverage")
    require(speculative.get("local_facts", {}).get("scheduler_policies", 0) >= 2, "speculative-decoding-serving-dev lacks scheduler policy coverage")
    tensor_core_gemm = next(row for row in profiles if row["id"] == "tensor-core-gemm-dev")
    require(tensor_core_gemm["status"] == "ready", "tensor-core-gemm-dev profile should be ready on this machine")
    require(tensor_core_gemm.get("local_facts", {}).get("status") == "tensor-core-gemm-ready", "tensor-core-gemm-dev did not complete")
    require(tensor_core_gemm.get("local_facts", {}).get("scenarios", 0) >= 5, "tensor-core-gemm-dev lacks scenarios")
    require(tensor_core_gemm.get("local_facts", {}).get("tensor_core_eligible", 0) >= 5, "tensor-core-gemm-dev lacks tensor-core coverage")
    persistent_kernels = next(row for row in profiles if row["id"] == "persistent-kernels-dev")
    require(persistent_kernels["status"] == "ready", "persistent-kernels-dev profile should be ready on this machine")
    require(persistent_kernels.get("local_facts", {}).get("status") == "persistent-kernels-ready", "persistent-kernels-dev did not complete")
    require(persistent_kernels.get("local_facts", {}).get("scenarios", 0) >= 6, "persistent-kernels-dev lacks scenarios")
    require(persistent_kernels.get("local_facts", {}).get("families", 0) >= 5, "persistent-kernels-dev lacks kernel family coverage")
    parallel_primitives = next(row for row in profiles if row["id"] == "parallel-primitives-dev")
    require(parallel_primitives["status"] == "ready", "parallel-primitives-dev profile should be ready on this machine")
    require(parallel_primitives.get("local_facts", {}).get("status") == "parallel-primitives-ready", "parallel-primitives-dev did not complete")
    require(parallel_primitives.get("local_facts", {}).get("scenarios", 0) >= 6, "parallel-primitives-dev lacks scenarios")
    require(parallel_primitives.get("local_facts", {}).get("primitives", 0) >= 6, "parallel-primitives-dev lacks primitive coverage")
    serving_engine = next(row for row in profiles if row["id"] == "serving-engine-comparison-dev")
    require(serving_engine["status"] == "ready", "serving-engine-comparison-dev profile should be ready on this machine")
    require(serving_engine.get("local_facts", {}).get("status") == "comparison-ready", "serving-engine-comparison-dev did not complete")
    require(serving_engine.get("local_facts", {}).get("engines", 0) >= 5, "serving-engine-comparison-dev lacks engine coverage")
    require(serving_engine.get("local_facts", {}).get("scenarios", 0) >= 5, "serving-engine-comparison-dev lacks scenario coverage")
    distributed_topology = next(row for row in profiles if row["id"] == "distributed-topology-dev")
    require(distributed_topology["status"] == "ready", "distributed-topology-dev profile should be ready on this machine")
    require(distributed_topology.get("local_facts", {}).get("status") == "topology-plan-ready", "distributed-topology-dev did not complete")
    require(distributed_topology.get("local_facts", {}).get("topologies", 0) >= 5, "distributed-topology-dev lacks topology coverage")
    require(distributed_topology.get("local_facts", {}).get("workloads", 0) >= 5, "distributed-topology-dev lacks workload coverage")
    distributed_collectives = next(row for row in profiles if row["id"] == "distributed-collectives-dev")
    require(distributed_collectives["status"] == "ready", "distributed-collectives-dev profile should be ready on this machine")
    require(distributed_collectives.get("local_facts", {}).get("status") == "distributed-collectives-ready", "distributed-collectives-dev did not complete")
    require(distributed_collectives.get("local_facts", {}).get("scenarios", 0) >= 6, "distributed-collectives-dev lacks scenarios")
    require(distributed_collectives.get("local_facts", {}).get("collectives", 0) >= 5, "distributed-collectives-dev lacks collective coverage")
    distributed_training = next(row for row in profiles if row["id"] == "distributed-training-optimizer-dev")
    require(distributed_training["status"] == "ready", "distributed-training-optimizer-dev profile should be ready on this machine")
    require(distributed_training.get("local_facts", {}).get("status") == "training-optimizer-ready", "distributed-training-optimizer-dev did not complete")
    require(distributed_training.get("local_facts", {}).get("scenarios", 0) >= 6, "distributed-training-optimizer-dev lacks scenarios")
    require(distributed_training.get("local_facts", {}).get("strategies", 0) >= 5, "distributed-training-optimizer-dev lacks strategy coverage")
    moe_routing = next(row for row in profiles if row["id"] == "moe-routing-all-to-all-dev")
    require(moe_routing["status"] == "ready", "moe-routing-all-to-all-dev profile should be ready on this machine")
    require(moe_routing.get("local_facts", {}).get("status") == "moe-routing-ready", "moe-routing-all-to-all-dev did not complete")
    require(moe_routing.get("local_facts", {}).get("scenarios", 0) >= 5, "moe-routing-all-to-all-dev lacks scenarios")
    require(moe_routing.get("local_facts", {}).get("tuning_required", 0) >= 1, "moe-routing-all-to-all-dev lacks tuning case")
    hardware_capacity = next(row for row in profiles if row["id"] == "hardware-capacity-dev")
    require(hardware_capacity["status"] == "ready", "hardware-capacity-dev profile should be ready on this machine")
    require(hardware_capacity.get("local_facts", {}).get("status") == "capacity-plan-ready", "hardware-capacity-dev did not complete")
    require(hardware_capacity.get("local_facts", {}).get("profiles", 0) >= 5, "hardware-capacity-dev lacks hardware profiles")
    require(hardware_capacity.get("local_facts", {}).get("workloads", 0) >= 5, "hardware-capacity-dev lacks workload coverage")
    require(hardware_capacity.get("local_facts", {}).get("recommendations", 0) >= 5, "hardware-capacity-dev lacks recommendations")
    quantization = next(row for row in profiles if row["id"] == "quantization-memory-dev")
    require(quantization["status"] == "ready", "quantization-memory-dev profile should be ready on this machine")
    require(quantization.get("local_facts", {}).get("status") == "quantization-ready", "quantization-memory-dev did not complete")
    require(quantization.get("local_facts", {}).get("formats", 0) >= 7, "quantization-memory-dev lacks format coverage")
    require(quantization.get("local_facts", {}).get("passed", 0) >= 4, "quantization-memory-dev lacks passing formats")
    numerical = next(row for row in profiles if row["id"] == "numerical-reproducibility-dev")
    require(numerical["status"] == "ready", "numerical-reproducibility-dev profile should be ready on this machine")
    require(numerical.get("local_facts", {}).get("status") == "reproducibility-ready", "numerical-reproducibility-dev did not complete")
    require(numerical.get("local_facts", {}).get("scenarios", 0) >= 5, "numerical-reproducibility-dev lacks scenarios")
    require(numerical.get("local_facts", {}).get("tolerance_reviews", 0) >= 1, "numerical-reproducibility-dev lacks tolerance-review evidence")
    cuda_graphs = next(row for row in profiles if row["id"] == "cuda-graphs-latency-dev")
    require(cuda_graphs["status"] == "ready", "cuda-graphs-latency-dev profile should be ready on this machine")
    require(cuda_graphs.get("local_facts", {}).get("status") == "cuda-graphs-ready", "cuda-graphs-latency-dev did not complete")
    require(cuda_graphs.get("local_facts", {}).get("scenarios", 0) >= 5, "cuda-graphs-latency-dev lacks scenarios")
    require(cuda_graphs.get("local_facts", {}).get("capture_ready", 0) >= 3, "cuda-graphs-latency-dev lacks capture-ready scenarios")
    scheduling = next(row for row in profiles if row["id"] == "multi-tenant-scheduling-dev")
    require(scheduling["status"] == "ready", "multi-tenant-scheduling-dev profile should be ready on this machine")
    require(scheduling.get("local_facts", {}).get("status") == "scheduling-ready", "multi-tenant-scheduling-dev did not complete")
    require(scheduling.get("local_facts", {}).get("policies", 0) >= 4, "multi-tenant-scheduling-dev lacks policy coverage")
    require(scheduling.get("local_facts", {}).get("tenants", 0) >= 5, "multi-tenant-scheduling-dev lacks tenant coverage")
    require(scheduling.get("local_facts", {}).get("accepted", 0) >= 4, "multi-tenant-scheduling-dev accepts too few tenants")
    custom_op = next(row for row in profiles if row["id"] == "custom-op-dev")
    require(custom_op["status"] == "ready", "custom-op-dev profile should be ready on this machine")
    require(custom_op.get("local_facts", {}).get("passed", 0) >= 4, "custom-op-dev lacks custom-op evidence")
    compiler_runtime = next(row for row in profiles if row["id"] == "compiler-runtime-inspection-dev")
    require(compiler_runtime["status"] == "ready", "compiler-runtime-inspection-dev profile should be ready on this machine")
    require(compiler_runtime.get("local_facts", {}).get("status") == "inspection-ready", "compiler-runtime-inspection-dev did not complete")
    require(compiler_runtime.get("local_facts", {}).get("sources", 0) >= 10, "compiler-runtime-inspection-dev lacks source coverage")
    require({"cuda", "triton", "custom-op", "hip"}.issubset(set(compiler_runtime.get("local_facts", {}).get("groups", []))), "compiler-runtime-inspection-dev lacks source groups")
    autotune = next(row for row in profiles if row["id"] == "autotune-dev")
    require(autotune["status"] == "ready", "autotune-dev profile should be ready on this machine")
    require(autotune.get("local_facts", {}).get("records", 0) >= 18, "autotune-dev lacks tuning records")
    model = next(row for row in profiles if row["id"] == "model-integration-dev")
    require(model["status"] == "ready", "model-integration-dev profile should be ready on this machine")
    require(model.get("local_facts", {}).get("passed", 0) >= 3, "model-integration-dev lacks model cases")
    regression = next(row for row in profiles if row["id"] == "regression-ledger-dev")
    require(regression["status"] == "ready", "regression-ledger-dev profile should be ready on this machine")
    require(regression.get("local_facts", {}).get("metrics", 0) >= 95, "regression-ledger-dev lacks regression metrics")
    require(regression.get("local_facts", {}).get("failed", 1) == 0, "regression-ledger-dev has failed metrics")
    promotion = next(row for row in profiles if row["id"] == "gpu-promotion-dev")
    require(promotion["status"] == "ready", "gpu-promotion-dev profile should be ready on this machine")
    require(promotion.get("local_facts", {}).get("steps", 0) >= 9, "gpu-promotion-dev lacks promotion steps")
    promotion_suite = next(row for row in profiles if row["id"] == "gpu-promotion-suite-dev")
    require(promotion_suite["status"] == "ready", "gpu-promotion-suite-dev profile should be ready on this machine")
    require(promotion_suite.get("local_facts", {}).get("commands", 0) >= 20, "gpu-promotion-suite-dev lacks command plan")
    import_lint = next(row for row in profiles if row["id"] == "gpu-import-lint-dev")
    require(import_lint["status"] == "ready", "gpu-import-lint-dev profile should be ready on this machine")
    require(import_lint.get("local_facts", {}).get("status") == "lint-clean", "gpu-import-lint-dev is not clean")
    require(import_lint.get("local_facts", {}).get("errors", 1) == 0, "gpu-import-lint-dev has errors")
    gpu_runs = next(row for row in profiles if row["id"] == "gpu-runs-dev")
    require(gpu_runs["status"] == "ready", "gpu-runs-dev profile should be ready on this machine")
    require(gpu_runs.get("local_facts", {}).get("runs", 0) >= 2, "gpu-runs-dev lacks imported runs")
    require(gpu_runs.get("local_facts", {}).get("promotion_steps", 0) >= 9, "gpu-runs-dev lacks promotion step coverage")
    gpu_provenance = next(row for row in profiles if row["id"] == "gpu-provenance-dev")
    require(gpu_provenance["status"] == "ready", "gpu-provenance-dev profile should be ready on this machine")
    require(gpu_provenance.get("local_facts", {}).get("status") == "provenance-clear", "gpu-provenance-dev lacks clear provenance")
    require(gpu_provenance.get("local_facts", {}).get("sample_runs", 0) >= 2, "gpu-provenance-dev lacks sample fixture accounting")
    require(gpu_provenance.get("local_facts", {}).get("host_collected_runs", 0) >= 1, "gpu-provenance-dev lacks host-collected accounting")
    measurement_queue = next(row for row in profiles if row["id"] == "gpu-measurement-queue-dev")
    require(measurement_queue["status"] == "ready", "gpu-measurement-queue-dev profile should be ready on this machine")
    require(measurement_queue.get("local_facts", {}).get("status") == "queue-ready", "gpu-measurement-queue-dev lacks queue-ready status")
    require(measurement_queue.get("local_facts", {}).get("tasks", 0) >= 9, "gpu-measurement-queue-dev lacks tasks")
    require(measurement_queue.get("local_facts", {}).get("failed_measured", 0) == 0, "gpu-measurement-queue-dev has failed measured tasks")
    acceptance_logic = next(row for row in profiles if row["id"] == "gpu-acceptance-logic-dev")
    require(acceptance_logic["status"] == "ready", "gpu-acceptance-logic-dev profile should be ready on this machine")
    require(acceptance_logic.get("local_facts", {}).get("status") == "passed", "gpu-acceptance-logic-dev did not pass")
    require(acceptance_logic.get("local_facts", {}).get("accepted_good", 0) >= 9, "gpu-acceptance-logic-dev did not accept good cases")
    require(acceptance_logic.get("local_facts", {}).get("rejected_bad", 0) >= 9, "gpu-acceptance-logic-dev did not reject bad cases")
    preflight = next(row for row in profiles if row["id"] == "gpu-host-preflight-dev")
    require(preflight["status"] == "ready", "gpu-host-preflight-dev profile should be ready on this machine")
    require(preflight.get("local_facts", {}).get("status") == "preflight-complete", "gpu-host-preflight-dev did not complete")
    require(preflight.get("local_facts", {}).get("steps", 0) >= 9, "gpu-host-preflight-dev lacks step coverage")
    gpu_handoff = next(row for row in profiles if row["id"] == "gpu-handoff-dev")
    require(gpu_handoff["status"] == "ready", "gpu-handoff-dev profile should be ready on this machine")
    require(gpu_handoff.get("local_facts", {}).get("commands", 0) >= 20, "gpu-handoff-dev lacks command coverage")
    assessment = next(row for row in profiles if row["id"] == "assessment-dev")
    require(assessment["status"] == "ready", "assessment-dev profile should be ready on this machine")
    require(assessment.get("local_facts", {}).get("concept_questions", 0) >= 10, "assessment-dev lacks concept questions")
    require(assessment.get("local_facts", {}).get("practical_tasks", 0) >= 8, "assessment-dev lacks practical tasks")
    assessment_grading = next(row for row in profiles if row["id"] == "assessment-grading-dev")
    require(assessment_grading["status"] == "ready", "assessment-grading-dev profile should be ready on this machine")
    require(assessment_grading.get("local_facts", {}).get("score", 0) == assessment_grading.get("local_facts", {}).get("max_score", -1), "assessment-grading-dev lacks full score")
    capstone = next(row for row in profiles if row["id"] == "capstone-acceptance-dev")
    require(capstone["status"] == "ready", "capstone-acceptance-dev profile should be ready on this machine")
    require(capstone.get("local_facts", {}).get("score", 0) == capstone.get("local_facts", {}).get("max_score", -1), "capstone-acceptance-dev lacks full acceptance score")
    for profile in profiles:
        require(profile.get("commands"), f"{profile['id']} missing commands")
        require(profile.get("evidence"), f"{profile['id']} missing evidence")
        require(profile.get("status") in {"ready", "source-ready-local-fallback", "blocked-by-runtime"}, f"{profile['id']} has invalid status")
    require((ROOT / "runtime-matrix" / "MATRIX.md").exists(), "missing runtime matrix Markdown")
    if SITE_PAGE.exists():
        page = SITE_PAGE.read_text(encoding="utf-8")
        require("GPUMODE runtime matrix" in page, "runtime matrix site page missing title")
        require("cpu-local" in page and "cuda-dev" in page and "serving-dev" in page and "kv-cache-paged-attention-dev" in page and "attention-serving-stack-dev" in page and "flash-attention-backward-dev" in page and "sparse-attention-kernels-dev" in page and "fused-training-kernels-dev" in page and "tensor-core-gemm-dev" in page and "serving-engine-comparison-dev" in page and "distributed-topology-dev" in page and "distributed-collectives-dev" in page and "distributed-training-optimizer-dev" in page and "moe-routing-all-to-all-dev" in page and "hardware-capacity-dev" in page and "quantization-memory-dev" in page and "numerical-reproducibility-dev" in page and "cuda-graphs-latency-dev" in page and "multi-tenant-scheduling-dev" in page and "compiler-runtime-inspection-dev" in page and "custom-op-dev" in page and "autotune-dev" in page and "model-integration-dev" in page and "regression-ledger-dev" in page and "gpu-promotion-dev" in page and "gpu-promotion-suite-dev" in page and "gpu-import-lint-dev" in page and "gpu-runs-dev" in page and "gpu-provenance-dev" in page and "gpu-measurement-queue-dev" in page and "gpu-acceptance-logic-dev" in page and "gpu-host-preflight-dev" in page and "gpu-handoff-dev" in page and "assessment-dev" in page and "assessment-grading-dev" in page and "capstone-acceptance-dev" in page, "runtime matrix site page missing profiles")
    facts = {
        "profiles": matrix.get("profile_count"),
        "ready": matrix.get("ready_profiles"),
        "fallback": matrix.get("fallback_profiles"),
        "blocked": matrix.get("blocked_profiles"),
        "torch_device": matrix.get("local_capabilities", {}).get("torch_device"),
        "nvcc": matrix.get("local_capabilities", {}).get("nvcc"),
    }
    print(json.dumps({"facts": facts, "failures": []}, indent=2))
    print("GPUMODE runtime matrix verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
