"""Run the next-stage agentic verification milestone as one aggregate job."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import os
import subprocess
import sys


ROOT = Path(__file__).resolve().parent.parent
SUBREPO = ROOT / "analog-digital-chip-design-eda"


def _last_json(text: str) -> dict:
    for line in reversed(text.splitlines()):
        try:
            value = json.loads(line)
            if isinstance(value, dict):
                return value
        except json.JSONDecodeError:
            continue
    return {"status": "blocked", "error": "subcommand emitted no JSON result"}


def _run(name: str, command: list[str], *, cwd: Path, output: Path, env: dict[str, str] | None = None) -> dict:
    completed = subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=False, env=env)
    record = {"name": name, "command": command, "cwd": str(cwd), "returncode": completed.returncode, "status": "passed" if completed.returncode == 0 else "blocked", "result": _last_json(completed.stdout), "stdout": completed.stdout, "stderr": completed.stderr}
    (output / f"{name}.stdout.log").write_text(completed.stdout, encoding="utf-8")
    (output / f"{name}.stderr.log").write_text(completed.stderr, encoding="utf-8")
    return record


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / ".artifacts/next-stage-milestone")
    parser.add_argument("--agent-backend", choices=("mock", "local"), default="mock")
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    matrix_env = os.environ.copy()
    if args.agent_backend == "mock":
        matrix_env["VERIFICATION_LLM_COMMAND"] = f"{sys.executable} {SUBREPO / 'scripts/mock_repository_agent_backend.py'}"
    records = []
    records.append(_run("repository-fail-to-pass", [sys.executable, "scripts/run_seeded_repository_scale_demo.py", "--output", str(output / "repository")], cwd=SUBREPO, output=output))
    records.append(_run("mutation-closure", [sys.executable, "scripts/run_seeded_multi_mutation_demo.py", "--output", str(output / "mutation")], cwd=SUBREPO, output=output))
    records.append(_run("parameterized-mutation-100", [sys.executable, "scripts/run_seeded_parameterized_mutation_campaign.py", "--output", str(output / "parameterized-mutation-100")], cwd=SUBREPO, output=output))
    records.append(_run("parameterized-mutation-100-integrity", [sys.executable, "scripts/check_parameterized_mutation_campaign.py", str(output / "parameterized-mutation-100" / "mutation-closure-report.json")], cwd=SUBREPO, output=output))
    records.append(_run("workstream2-mutation-1000", [sys.executable, "scripts/run_workstream2_1000_mutation_campaign.py", "--output", str(output / "workstream2-mutation-1000")], cwd=SUBREPO, output=output))
    records.append(_run("workstream2-mutation-1000-integrity", [sys.executable, "scripts/check_workstream2_1000_mutation_campaign.py", str(output / "workstream2-mutation-1000" / "mutation-closure-report.json")], cwd=SUBREPO, output=output))
    records.append(_run("real-multimodule-rtl-catalog", [sys.executable, str(ROOT / "scripts/catalog_real_multimodule_rtl.py"), "--output", str(output / "real-multimodule-rtl-catalog")], cwd=ROOT, output=output))
    records.append(_run("real-multimodule-rtl-catalog-integrity", [sys.executable, str(ROOT / "scripts/check_real_multimodule_rtl_catalog.py"), str(output / "real-multimodule-rtl-catalog" / "real-multimodule-rtl-catalog.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-peripheral-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_peripheral_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "real-openlane-peripheral-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-peripheral-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_peripheral_agent_repair.py"), str(output / "real-openlane-peripheral-agent-repair" / "real-openlane-peripheral-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-multiclock-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_multiclock_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "real-openlane-multiclock-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-multiclock-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_multiclock_agent_repair.py"), str(output / "real-openlane-multiclock-agent-repair" / "real-openlane-multiclock-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-operation-partition-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_operation_partition_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "real-openlane-operation-partition-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-operation-partition-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_operation_partition_agent_repair.py"), str(output / "real-openlane-operation-partition-agent-repair" / "real-openlane-operation-partition-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-error-budget-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_error_budget_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "real-openlane-error-budget-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-error-budget-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_error_budget_agent_repair.py"), str(output / "real-openlane-error-budget-agent-repair" / "real-openlane-error-budget-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-causal-localization", [sys.executable, str(ROOT / "scripts/run_real_causal_localization.py"), "--output", str(output / "real-causal-localization")], cwd=ROOT, output=output))
    records.append(_run("real-causal-localization-integrity", [sys.executable, str(ROOT / "scripts/check_real_causal_localization.py"), str(output / "real-causal-localization" / "real-causal-localization-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-multiclock-causal-localization", [sys.executable, str(ROOT / "scripts/run_real_multiclock_causal_localization.py"), "--output", str(output / "real-multiclock-causal-localization")], cwd=ROOT, output=output))
    records.append(_run("real-multiclock-causal-localization-integrity", [sys.executable, str(ROOT / "scripts/check_real_multiclock_causal_localization.py"), str(output / "real-multiclock-causal-localization" / "real-multiclock-causal-localization-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-error-budget-causal-localization", [sys.executable, str(ROOT / "scripts/run_real_error_budget_causal_localization.py"), "--output", str(output / "real-error-budget-causal-localization")], cwd=ROOT, output=output))
    records.append(_run("real-error-budget-causal-localization-integrity", [sys.executable, str(ROOT / "scripts/check_real_error_budget_causal_localization.py"), str(output / "real-error-budget-causal-localization" / "real-error-budget-causal-localization-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-peripheral-causal-localization", [sys.executable, str(ROOT / "scripts/run_real_peripheral_causal_localization.py"), "--output", str(output / "real-peripheral-causal-localization")], cwd=ROOT, output=output))
    records.append(_run("real-peripheral-causal-localization-integrity", [sys.executable, str(ROOT / "scripts/check_real_peripheral_causal_localization.py"), str(output / "real-peripheral-causal-localization" / "real-peripheral-causal-localization-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-operation-partition-causal-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_operation_partition_agent_repair.py"), "--backend", args.agent_backend, "--causal-report", str(output / "real-causal-localization" / "real-causal-localization-report.json"), "--output", str(output / "real-openlane-operation-partition-causal-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-operation-partition-causal-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_operation_partition_agent_repair.py"), str(output / "real-openlane-operation-partition-causal-agent-repair" / "real-openlane-operation-partition-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-error-budget-causal-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_error_budget_agent_repair.py"), "--backend", args.agent_backend, "--causal-report", str(output / "real-error-budget-causal-localization" / "real-error-budget-causal-localization-report.json"), "--output", str(output / "real-openlane-error-budget-causal-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-error-budget-causal-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_error_budget_agent_repair.py"), str(output / "real-openlane-error-budget-causal-agent-repair" / "real-openlane-error-budget-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-peripheral-causal-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_peripheral_agent_repair.py"), "--backend", args.agent_backend, "--causal-report", str(output / "real-peripheral-causal-localization" / "real-peripheral-causal-localization-report.json"), "--output", str(output / "real-openlane-peripheral-causal-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-peripheral-causal-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_peripheral_agent_repair.py"), str(output / "real-openlane-peripheral-causal-agent-repair" / "real-openlane-peripheral-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("real-openlane-multiclock-causal-agent-repair", [sys.executable, str(ROOT / "scripts/run_real_multiclock_agent_repair.py"), "--backend", args.agent_backend, "--causal-report", str(output / "real-multiclock-causal-localization" / "real-multiclock-causal-localization-report.json"), "--output", str(output / "real-openlane-multiclock-causal-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("real-openlane-multiclock-causal-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_real_multiclock_causal_agent_repair.py"), str(output / "real-openlane-multiclock-causal-agent-repair" / "real-openlane-multiclock-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("heldout-mutation-evaluation", [sys.executable, "scripts/run_seeded_heldout_evaluation.py", "--output", str(output / "heldout")], cwd=SUBREPO, output=output))
    records.append(_run("repository-agent-matrix", [sys.executable, "scripts/run_seeded_repository_agent_matrix.py", "--backend", args.agent_backend, "--output", str(output / "agent-matrix")], cwd=SUBREPO, output=output, env=matrix_env))
    records.append(_run("repository-agent-matrix-integrity", [sys.executable, "scripts/check_seeded_repository_agent_matrix.py", str(output / "agent-matrix" / "repository-agent-matrix-report.json")], cwd=SUBREPO, output=output))
    records.append(_run("agent-repair-closure", [sys.executable, "scripts/run_seeded_agent_repair_closure.py", "--backend", args.agent_backend, "--output", str(output / "agent-repair-closure")], cwd=SUBREPO, output=output, env=matrix_env))
    records.append(_run("agent-causal-closure-integrity", [sys.executable, "scripts/check_seeded_agent_causal_closure.py", str(output / "agent-repair-closure" / "seeded-agent-repair-closure-report.json")], cwd=SUBREPO, output=output))
    records.append(_run("coverage-gap-agent", [sys.executable, "scripts/run_coverage_gap_agent.py", "--output", str(output / "coverage")], cwd=SUBREPO, output=output))
    records.append(_run("coverage-closure", [sys.executable, "scripts/run_seeded_coverage_closure.py", "--output", str(output / "coverage-closure")], cwd=SUBREPO, output=output))
    records.append(_run("repaired-induction", [sys.executable, "scripts/run_repaired_inductive_suite.py", "--output", str(output / "induction")], cwd=SUBREPO, output=output))
    records.append(_run("formal-proof-closure", [sys.executable, "scripts/run_formal_proof_closure_suite.py", "--output", str(output / "formal-proof-closure")], cwd=SUBREPO, output=output))
    records.append(_run("formal-proof-closure-integrity", [sys.executable, "scripts/check_formal_proof_closure_suite.py", str(output / "formal-proof-closure" / "formal-proof-closure-suite-report.json")], cwd=SUBREPO, output=output))
    records.append(_run("security-red-blue", [sys.executable, "scripts/run_security_regblock_demo.py", "--output", str(output / "security")], cwd=SUBREPO, output=output))
    records.append(_run("security-policy-campaign", [sys.executable, "scripts/run_security_regblock_campaign.py", "--output", str(output / "security-policy-campaign")], cwd=SUBREPO, output=output))
    records.append(_run("security-policy-campaign-integrity", [sys.executable, "scripts/check_security_regblock_campaign.py", str(output / "security-policy-campaign" / "security-campaign-report.json")], cwd=SUBREPO, output=output))
    records.append(_run("openroad-functional", [sys.executable, str(ROOT / "scripts/run_openroad_gcd_functional_task.py"), "--output", str(output / "openroad")], cwd=ROOT, output=output))
    records.append(_run("openroad-fifo-functional", [sys.executable, str(ROOT / "scripts/run_openroad_fifo_functional_task.py"), "--output", str(output / "openroad-fifo")], cwd=ROOT, output=output))
    records.append(_run("openroad-fifo-agent-repair-closure", [sys.executable, str(ROOT / "scripts/run_openroad_fifo_agent_repair_closure.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-fifo-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-fifo-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_fifo_agent_repair_closure.py"), str(output / "openroad-fifo-agent-repair" / "openroad-fifo-agent-repair-closure-report.json")], cwd=ROOT, output=output))
    records.append(_run("openroad-aes-functional", [sys.executable, str(ROOT / "scripts/run_openroad_aes_functional_task.py"), "--output", str(output / "openroad-aes")], cwd=ROOT, output=output))
    records.append(_run("openroad-native-compile", [sys.executable, str(ROOT / "scripts/run_openroad_native_compile_suite.py"), "--output", str(output / "openroad-native")], cwd=ROOT, output=output))
    records.append(_run("openroad-agent-repair-closure", [sys.executable, str(ROOT / "scripts/run_openroad_agent_repair_closure.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-aes-agent-repair-closure", [sys.executable, str(ROOT / "scripts/run_openroad_aes_agent_repair_closure.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-aes-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-gallery-agent-repair", [sys.executable, str(ROOT / "scripts/run_openroad_historical_gallery_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-historical-gallery-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-gallery-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_historical_gallery_agent_repair.py"), str(output / "openroad-historical-gallery-agent-repair" / "openroad-historical-gallery-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-timeout-agent-repair-closure", [sys.executable, str(ROOT / "scripts/run_openlane_timeout_agent_repair_closure.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-timeout-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-gui-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_gui_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-gui-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-gui-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_gui_agent_repair.py"), str(output / "openlane-historical-gui-agent-repair" / "openlane-historical-gui-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-tcl-env-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_tcl_env_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-tcl-env-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-tcl-env-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_tcl_env_agent_repair.py"), str(output / "openlane-historical-tcl-env-agent-repair" / "openlane-historical-tcl-env-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-clock-port-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_clock_port_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-clock-port-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-clock-port-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_clock_port_agent_repair.py"), str(output / "openlane-historical-clock-port-agent-repair" / "openlane-historical-clock-port-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-pin-order-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_pin_order_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-pin-order-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-pin-order-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_pin_order_agent_repair.py"), str(output / "openlane-historical-pin-order-agent-repair" / "openlane-historical-pin-order-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("cross-sim-historical-parasitics-agent-repair", [sys.executable, str(ROOT / "scripts/run_cross_sim_historical_parasitics_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "cross-sim-historical-parasitics-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("cross-sim-historical-parasitics-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_cross_sim_historical_parasitics_agent_repair.py"), str(output / "cross-sim-historical-parasitics-agent-repair" / "cross-sim-historical-parasitics-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("historical-fix-candidate-mining", [sys.executable, str(ROOT / "scripts/mine_historical_fix_candidates.py"), "--limit-per-repository", "1000", "--output", str(output / "historical-fix-candidates")], cwd=ROOT, output=output))
    records.append(_run("historical-fix-candidate-mining-integrity", [sys.executable, str(ROOT / "scripts/check_historical_fix_candidates.py"), str(output / "historical-fix-candidates" / "historical-fix-candidate-manifest.json")], cwd=ROOT, output=output))
    records.append(_run("historical-replay-split-integrity", [sys.executable, str(ROOT / "scripts/check_historical_replay_split.py"), str(output / "historical-fix-candidates" / "historical-fix-candidate-manifest.json")], cwd=ROOT, output=output))
    records.append(_run("historical-replay-queue", [sys.executable, str(ROOT / "scripts/build_historical_replay_queue.py"), str(output / "historical-fix-candidates" / "historical-fix-candidate-manifest.json"), "--output", str(output / "historical-replay-queue.json")], cwd=ROOT, output=output))
    records.append(_run("historical-replay-queue-integrity", [sys.executable, str(ROOT / "scripts/check_historical_replay_queue.py"), str(output / "historical-replay-queue.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-io-sequence-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_io_sequence_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-io-sequence-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-io-sequence-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_io_sequence_agent_repair.py"), str(output / "openlane-historical-io-sequence-agent-repair" / "openlane-historical-io-sequence-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-resizer-env-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_resizer_env_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-resizer-env-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-resizer-env-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_resizer_env_agent_repair.py"), str(output / "openlane-historical-resizer-env-agent-repair" / "openlane-historical-resizer-env-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-def-template-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_def_template_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-def-template-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-def-template-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_def_template_agent_repair.py"), str(output / "openlane-historical-def-template-agent-repair" / "openlane-historical-def-template-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-route-obs-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_route_obs_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-route-obs-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-route-obs-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_route_obs_agent_repair.py"), str(output / "openlane-historical-route-obs-agent-repair" / "openlane-historical-route-obs-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-design-path-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_design_path_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-design-path-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-design-path-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_design_path_agent_repair.py"), str(output / "openlane-historical-design-path-agent-repair" / "openlane-historical-design-path-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-macro-units-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_macro_units_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-macro-units-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-macro-units-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_macro_units_agent_repair.py"), str(output / "openlane-historical-macro-units-agent-repair" / "openlane-historical-macro-units-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-report-path-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_report_path_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-report-path-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-report-path-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_report_path_agent_repair.py"), str(output / "openlane-historical-report-path-agent-repair" / "openlane-historical-report-path-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-yosys-check-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_yosys_check_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-yosys-check-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-yosys-check-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_yosys_check_agent_repair.py"), str(output / "openlane-historical-yosys-check-agent-repair" / "openlane-historical-yosys-check-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-sta-blackbox-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_sta_blackbox_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-sta-blackbox-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-sta-blackbox-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_sta_blackbox_agent_repair.py"), str(output / "openlane-historical-sta-blackbox-agent-repair" / "openlane-historical-sta-blackbox-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-lec-liberty-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_lec_liberty_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-lec-liberty-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-lec-liberty-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_lec_liberty_agent_repair.py"), str(output / "openlane-historical-lec-liberty-agent-repair" / "openlane-historical-lec-liberty-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-resizer-typo-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_resizer_typo_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-resizer-typo-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-resizer-typo-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_resizer_typo_agent_repair.py"), str(output / "openlane-historical-resizer-typo-agent-repair" / "openlane-historical-resizer-typo-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-linter-defines-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_linter_defines_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-linter-defines-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-linter-defines-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_linter_defines_agent_repair.py"), str(output / "openlane-historical-linter-defines-agent-repair" / "openlane-historical-linter-defines-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-placement-order-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_placement_order_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-placement-order-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-placement-order-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_placement_order_agent_repair.py"), str(output / "openlane-historical-placement-order-agent-repair" / "openlane-historical-placement-order-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-lec-catch-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_lec_catch_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-lec-catch-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-lec-catch-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_lec_catch_agent_repair.py"), str(output / "openlane-historical-lec-catch-agent-repair" / "openlane-historical-lec-catch-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-irdrop-args-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_irdrop_args_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-irdrop-args-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-irdrop-args-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_irdrop_args_agent_repair.py"), str(output / "openlane-historical-irdrop-args-agent-repair" / "openlane-historical-irdrop-args-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-drc-file-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_drc_file_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-drc-file-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-drc-file-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_drc_file_agent_repair.py"), str(output / "openlane-historical-drc-file-agent-repair" / "openlane-historical-drc-file-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-sdc-override-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_sdc_override_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-sdc-override-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-sdc-override-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_sdc_override_agent_repair.py"), str(output / "openlane-historical-sdc-override-agent-repair" / "openlane-historical-sdc-override-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-latest-run-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_latest_run_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-latest-run-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-latest-run-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_latest_run_agent_repair.py"), str(output / "openlane-historical-latest-run-agent-repair" / "openlane-historical-latest-run-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-bm64-lint-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_bm64_lint_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-bm64-lint-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-bm64-lint-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_bm64_lint_agent_repair.py"), str(output / "openlane-historical-bm64-lint-agent-repair" / "openlane-historical-bm64-lint-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-flow-endpoint-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_flow_endpoint_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-flow-endpoint-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-flow-endpoint-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_flow_endpoint_agent_repair.py"), str(output / "openlane-historical-flow-endpoint-agent-repair" / "openlane-historical-flow-endpoint-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("cross-sim-historical-accuracy-agent-repair", [sys.executable, str(ROOT / "scripts/run_cross_sim_historical_accuracy_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "cross-sim-historical-accuracy-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("cross-sim-historical-accuracy-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_cross_sim_historical_accuracy_agent_repair.py"), str(output / "cross-sim-historical-accuracy-agent-repair" / "cross-sim-historical-accuracy-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openroad-historical-cached-copy-agent-repair", [sys.executable, str(ROOT / "scripts/run_openroad_historical_cached_copy_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-historical-cached-copy-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-cached-copy-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_historical_cached_copy_agent_repair.py"), str(output / "openroad-historical-cached-copy-agent-repair" / "openroad-historical-cached-copy-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-synth-analyze-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_synth_analyze_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-synth-analyze-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-synth-analyze-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_synth_analyze_agent_repair.py"), str(output / "openlane-historical-synth-analyze-agent-repair" / "openlane-historical-synth-analyze-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-synth-explore-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_synth_explore_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-synth-explore-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-synth-explore-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_synth_explore_agent_repair.py"), str(output / "openlane-historical-synth-explore-agent-repair" / "openlane-historical-synth-explore-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openroad-historical-cts-snapshot-agent-repair", [sys.executable, str(ROOT / "scripts/run_openroad_historical_cts_snapshot_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-historical-cts-snapshot-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-cts-snapshot-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_historical_cts_snapshot_agent_repair.py"), str(output / "openroad-historical-cts-snapshot-agent-repair" / "openroad-historical-cts-snapshot-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openroad-historical-antenna-limit-agent-repair", [sys.executable, str(ROOT / "scripts/run_openroad_historical_antenna_limit_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-historical-antenna-limit-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-antenna-limit-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_historical_antenna_limit_agent_repair.py"), str(output / "openroad-historical-antenna-limit-agent-repair" / "openroad-historical-antenna-limit-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-config-glob-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_config_glob_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-config-glob-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-config-glob-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_config_glob_agent_repair.py"), str(output / "openlane-historical-config-glob-agent-repair" / "openlane-historical-config-glob-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openroad-historical-stale-target-agent-repair", [sys.executable, str(ROOT / "scripts/run_openroad_historical_stale_target_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-historical-stale-target-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-stale-target-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_historical_stale_target_agent_repair.py"), str(output / "openroad-historical-stale-target-agent-repair" / "openroad-historical-stale-target-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-halo-width-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_halo_width_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-halo-width-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-halo-width-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_halo_width_agent_repair.py"), str(output / "openlane-historical-halo-width-agent-repair" / "openlane-historical-halo-width-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-issue-device-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_issue_device_path_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-issue-device-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-issue-device-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_issue_device_path_agent_repair.py"), str(output / "openlane-historical-issue-device-agent-repair" / "openlane-historical-issue-device-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-podman-mount-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_podman_mount_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-podman-mount-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-podman-mount-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_podman_mount_agent_repair.py"), str(output / "openlane-historical-podman-mount-agent-repair" / "openlane-historical-podman-mount-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-lec-readlib-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_lec_readlib_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-lec-readlib-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-lec-readlib-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_lec_readlib_agent_repair.py"), str(output / "openlane-historical-lec-readlib-agent-repair" / "openlane-historical-lec-readlib-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-jenkins-pdk-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_jenkins_pdk_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-jenkins-pdk-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-jenkins-pdk-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_jenkins_pdk_agent_repair.py"), str(output / "openlane-historical-jenkins-pdk-agent-repair" / "openlane-historical-jenkins-pdk-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-go-install-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_go_install_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-go-install-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-go-install-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_go_install_agent_repair.py"), str(output / "openlane-historical-go-install-agent-repair" / "openlane-historical-go-install-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-io-read-def-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_io_read_def_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-io-read-def-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-io-read-def-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_io_read_def_agent_repair.py"), str(output / "openlane-historical-io-read-def-agent-repair" / "openlane-historical-io-read-def-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-remove-nets-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_remove_nets_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-remove-nets-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-remove-nets-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_remove_nets_agent_repair.py"), str(output / "openlane-historical-remove-nets-agent-repair" / "openlane-historical-remove-nets-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-antenna-margin-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_antenna_margin_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-antenna-margin-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-antenna-margin-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_antenna_margin_agent_repair.py"), str(output / "openlane-historical-antenna-margin-agent-repair" / "openlane-historical-antenna-margin-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openroad-historical-estimate-parasitics-agent-repair", [sys.executable, str(ROOT / "scripts/run_openroad_historical_estimate_parasitics_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openroad-historical-estimate-parasitics-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openroad-historical-estimate-parasitics-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openroad_historical_estimate_parasitics_agent_repair.py"), str(output / "openroad-historical-estimate-parasitics-agent-repair" / "openroad-historical-estimate-parasitics-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-klayout-design-name-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_klayout_design_name_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-klayout-design-name-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-klayout-design-name-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_klayout_design_name_agent_repair.py"), str(output / "openlane-historical-klayout-design-name-agent-repair" / "openlane-historical-klayout-design-name-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-ioplacer-extension-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_ioplacer_extension_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-ioplacer-extension-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-ioplacer-extension-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_ioplacer_extension_agent_repair.py"), str(output / "openlane-historical-ioplacer-extension-agent-repair" / "openlane-historical-ioplacer-extension-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-threads-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_threads_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-threads-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-threads-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_threads_agent_repair.py"), str(output / "openlane-historical-threads-agent-repair" / "openlane-historical-threads-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-jenkins-tag-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_jenkins_tag_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-jenkins-tag-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-jenkins-tag-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_jenkins_tag_agent_repair.py"), str(output / "openlane-historical-jenkins-tag-agent-repair" / "openlane-historical-jenkins-tag-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-save-def-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_save_def_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-save-def-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-save-def-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_save_def_agent_repair.py"), str(output / "openlane-historical-save-def-agent-repair" / "openlane-historical-save-def-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-historical-macro-rotation-agent-repair", [sys.executable, str(ROOT / "scripts/run_openlane_historical_macro_rotation_agent_repair.py"), "--backend", args.agent_backend, "--output", str(output / "openlane-historical-macro-rotation-agent-repair")], cwd=ROOT, output=output, env=matrix_env))
    records.append(_run("openlane-historical-macro-rotation-agent-repair-integrity", [sys.executable, str(ROOT / "scripts/check_openlane_historical_macro_rotation_agent_repair.py"), str(output / "openlane-historical-macro-rotation-agent-repair" / "openlane-historical-macro-rotation-agent-repair-report.json")], cwd=ROOT, output=output))
    records.append(_run("openlane-native-compile", [sys.executable, str(ROOT / "scripts/run_openlane_native_compile_suite.py"), "--output", str(output / "openlane")], cwd=ROOT, output=output))
    agent_env = os.environ.copy()
    if args.agent_backend == "mock":
        agent_env["VERIFICATION_LLM_COMMAND"] = f"{sys.executable} {SUBREPO / 'scripts/mock_repository_agent_backend.py'}"
    agent_code = "from verification_platform.repository_agent import run_repository_agent; import json; r=run_repository_agent(task_id='seeded-counter-hold', source_revision='counter-v1', evidence=['failure.log','rtl/counter.sv'], failure_context='counter increments while enable is low', repair_before=\"else\\n      counter_q <= counter_q + 4'd1; // SEEDED_BUG: missing enable guard\", repair_after=\"else if (enable)\\n      counter_q <= counter_q + 4'd1;\", repair_source=r'" + str(SUBREPO / "benchmarks/seeded_counter/counter.sv") + "', backend='local', output_root=r'" + str(output / "agent") + "'); print(json.dumps({'status':r['team']['status'],'handoffs':len(r['team']['handoffs']),'patch_candidate':r.get('patch_candidate',{}).get('status',r.get('patch_candidate_status'))}))"
    records.append(_run("agent-handoff", [sys.executable, "-c", agent_code], cwd=SUBREPO, output=output, env=agent_env))
    records.append(_run("spec-grounded-assertion-matrix", [sys.executable, "scripts/run_four_workstream_assertion_matrix.py", "--output", str(output / "assertion-matrix")], cwd=SUBREPO, output=output, env=matrix_env))
    records.append(_run("spec-grounded-assertion-matrix-integrity", [sys.executable, str(ROOT / "scripts/check_assertion_matrix.py"), str(output / "assertion-matrix" / "matrix-result.json")], cwd=ROOT, output=output))
    report = {
        "schema_version": "next-stage-milestone-report-v1",
        "components": [{"name": item["name"], "status": item["status"], "returncode": item["returncode"], "result": item["result"]} for item in records],
        "agent_backend": args.agent_backend,
        "all_passed": all(item["status"] == "passed" for item in records),
        "claim_boundary": "aggregate acceptance of declared seeded, local OpenROAD, and fixture-agent slices; not SOTA benchmark completion or production signoff",
    }
    report["report_sha256"] = hashlib.sha256(json.dumps(report, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    (output / "next-stage-milestone-report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"status": "passed" if report["all_passed"] else "blocked", "components": [(item["name"], item["status"]) for item in records], "report": str(output / "next-stage-milestone-report.json")}, sort_keys=True))
    return 0 if report["all_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
