// Generated by labs/analog/analog-in-memory-foundation-model-hardware/python/generate_micro_tile_rtl_vectors.py
// Do not edit by hand; edit the analog vector generator instead.
        run_case("qkv_analog_readout_accepted", 4'd1, 1'b1, 8'd11, 1'b1, 10'd3, 16'd32, 2'd1, 4'd1, 8'd0, 16'd0, 16'd1, 16'd0, 16'd0, 2'd0);
        run_case("qkv_residual_forces_fallback", 4'd1, 1'b1, 8'd12, 1'b1, 10'd40, 16'd32, 2'd0, 4'd10, 8'd12, 16'd1, 16'd1, 16'd1, 16'd0, 2'd0);
        run_case("qkv_stale_calibration_fallback", 4'd1, 1'b1, 8'd17, 1'b1, 10'd3, 16'd2048, 2'd0, 4'd11, 8'd17, 16'd2, 16'd1, 16'd1, 16'd1, 2'd1);
        run_case("qkv_disabled_tile_fallback", 4'd1, 1'b1, 8'd13, 1'b0, 10'd3, 16'd32, 2'd0, 4'd9, 8'd13, 16'd3, 16'd1, 16'd1, 16'd1, 2'd1);
        run_case("attention_score_hybrid_review", 4'd2, 1'b1, 8'd14, 1'b1, 10'd3, 16'd32, 2'd2, 4'd2, 8'd13, 16'd3, 16'd1, 16'd1, 16'd1, 2'd1);
        run_case("softmax_partition_digital", 4'd4, 1'b1, 8'd15, 1'b1, 10'd3, 16'd32, 2'd0, 4'd0, 8'd13, 16'd3, 16'd1, 16'd1, 16'd1, 2'd1);
        run_case("missing_weights_partition_digital", 4'd1, 1'b0, 8'd16, 1'b1, 10'd3, 16'd32, 2'd0, 4'd3, 8'd13, 16'd3, 16'd1, 16'd1, 16'd1, 2'd1);
        run_case("second_residual_disables_tile", 4'd1, 1'b1, 8'd18, 1'b1, 10'd44, 16'd32, 2'd0, 4'd10, 8'd18, 16'd4, 16'd1, 16'd2, 16'd1, 2'd2);
