// Generated by labs/analog/analog-in-memory-foundation-model-hardware/python/model_impact_governor_requests.py
// Do not edit by hand; edit the model-impact generator instead.
        run_case("model_all_digital_reference", 1'b1, 1'b0, 8'd0, 4'd4, 8'd96, 8'd0, 2'd0, 2'd0, 4'd1, 8'd0);
        run_case("model_measured_fixed_projection_tile", 1'b1, 1'b1, 8'd6, 4'd4, 8'd96, 8'd6, 2'd1, 2'd0, 4'd6, 8'd12);
        run_case("model_measured_projection_stressed_tile", 1'b1, 1'b1, 8'd40, 4'd4, 8'd224, 8'd14, 2'd0, 2'd0, 4'd4, 8'd14);
        run_case("model_measured_attention_scores_analog", 1'b1, 1'b1, 8'd40, 4'd4, 8'd208, 8'd10, 2'd0, 2'd0, 4'd4, 8'd10);
        run_case("model_measured_logits_analog", 1'b1, 1'b1, 8'd40, 4'd4, 8'd224, 8'd12, 2'd0, 2'd0, 4'd4, 8'd12);
        run_case("model_backend_dense1.matmul", 1'b1, 1'b1, 8'd6, 4'd4, 8'd96, 8'd6, 2'd1, 2'd0, 4'd6, 8'd12);
        run_case("model_backend_dense1.bias", 1'b1, 1'b0, 8'd0, 4'd4, 8'd128, 8'd0, 2'd0, 2'd0, 4'd1, 8'd0);
        run_case("model_backend_dense1.relu", 1'b1, 1'b0, 8'd0, 4'd4, 8'd128, 8'd0, 2'd0, 2'd0, 4'd1, 8'd0);
        run_case("model_backend_dense2.matmul", 1'b1, 1'b1, 8'd6, 4'd4, 8'd96, 8'd6, 2'd1, 2'd0, 4'd6, 8'd12);
        run_case("model_backend_dense2.bias", 1'b1, 1'b0, 8'd0, 4'd4, 8'd128, 8'd0, 2'd0, 2'd0, 4'd1, 8'd0);
