"""Refresh the GPUMODE metadata-backed curriculum and site."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def run(cmd: list[str]) -> None:
    print("$", " ".join(cmd))
    subprocess.run(cmd, cwd=ROOT, check=True)


def main() -> None:
    run([sys.executable, "scripts/download_gpumode_transcripts.py", "--metadata-only"])
    run([sys.executable, "scripts/build_curriculum.py"])
    run([sys.executable, "scripts/build_workbench.py"])
    run([sys.executable, "scripts/build_gpu_programming_projects.py"])
    run([sys.executable, "scripts/run_gpu_programming_projects.py"])
    run([sys.executable, "scripts/build_gpu_project_notebooks.py"])
    run([sys.executable, "scripts/build_gpu_project_capstone.py"])
    run([sys.executable, "scripts/build_lesson_labs.py"])
    run([sys.executable, "scripts/run_lesson_labs.py"])
    run([sys.executable, "scripts/build_comprehensive_lab_plan.py"])
    run([sys.executable, "scripts/run_comprehensive_labs.py"])
    run([sys.executable, "scripts/build_kernel_benchmark_plan.py"])
    run([sys.executable, "scripts/run_kernel_benchmarks.py"])
    run([sys.executable, "scripts/run_compiler_runtime_inspection.py"])
    run([sys.executable, "scripts/run_tensor_core_gemm.py"])
    run([sys.executable, "scripts/run_persistent_kernels.py"])
    run([sys.executable, "scripts/run_parallel_primitives.py"])
    run([sys.executable, "scripts/run_custom_ops.py"])
    run([sys.executable, "scripts/build_autotune_db.py"])
    run([sys.executable, "scripts/run_model_integration.py"])
    run([sys.executable, "scripts/run_serving_traces.py"])
    run([sys.executable, "scripts/run_kv_cache_paged_attention.py"])
    run([sys.executable, "scripts/run_attention_serving_stack.py"])
    run([sys.executable, "scripts/run_flash_attention_backward.py"])
    run([sys.executable, "scripts/run_sparse_attention_kernels.py"])
    run([sys.executable, "scripts/run_fused_training_kernels.py"])
    run([sys.executable, "scripts/run_serving_engine_comparison.py"])
    run([sys.executable, "scripts/run_speculative_decoding_serving.py"])
    run([sys.executable, "scripts/run_distributed_topology.py"])
    run([sys.executable, "scripts/run_distributed_collectives.py"])
    run([sys.executable, "scripts/run_distributed_collectives_benchmark.py"])
    run([sys.executable, "scripts/run_distributed_training_optimizer.py"])
    run([sys.executable, "scripts/run_moe_routing_all_to_all.py"])
    run([sys.executable, "scripts/run_hardware_capacity_plan.py"])
    run([sys.executable, "scripts/run_quantization_memory_formats.py"])
    run([sys.executable, "scripts/run_numerical_reproducibility.py"])
    run([sys.executable, "scripts/run_cuda_graphs_latency.py"])
    run([sys.executable, "scripts/run_multi_tenant_gpu_scheduling.py"])
    run([sys.executable, "scripts/build_regression_ledger.py"])
    run([sys.executable, "scripts/build_gpu_promotion.py"])
    run([sys.executable, "scripts/run_gpu_host_preflight.py"])
    run([sys.executable, "scripts/run_gpu_promotion_suite.py", "--run-id", "local-suite-dry-run"])
    run([sys.executable, "scripts/lint_gpu_run_imports.py"])
    run([sys.executable, "scripts/build_gpu_runs.py"])
    run([sys.executable, "scripts/build_gpu_provenance.py"])
    run([sys.executable, "scripts/build_gpu_measurement_queue.py"])
    run([sys.executable, "scripts/verify_gpu_acceptance_logic.py"])
    run([sys.executable, "scripts/build_gpu_handoff.py"])
    run([sys.executable, "scripts/build_assessment.py"])
    run([sys.executable, "scripts/grade_assessment.py"])
    run([sys.executable, "scripts/run_profiler_evidence.py"])
    run([sys.executable, "scripts/build_teaching_pages.py"])
    run([sys.executable, "scripts/build_worked_walkthroughs.py"])
    run([sys.executable, "build_site.py"])
    run([sys.executable, "scripts/build_end_to_end_audit.py"])
    run([sys.executable, "scripts/build_capstone_acceptance.py"])
    run([sys.executable, "scripts/build_runtime_matrix.py"])
    run([sys.executable, "build_site.py"])
    run([sys.executable, "scripts/build_end_to_end_audit.py"])
    run([sys.executable, "scripts/build_capstone_acceptance.py"])
    run([sys.executable, "scripts/build_runtime_matrix.py"])
    run([sys.executable, "build_site.py"])
    run([sys.executable, "scripts/verify_workbench.py"])
    run([sys.executable, "scripts/verify_gpu_workbench_program.py"])
    run([sys.executable, "scripts/verify_gpu_programming_projects.py"])
    run([sys.executable, "scripts/verify_lesson_labs.py"])
    run([sys.executable, "scripts/verify_comprehensive_labs.py"])
    run([sys.executable, "scripts/verify_kernel_benchmarks.py"])
    run([sys.executable, "scripts/verify_compiler_runtime_inspection.py"])
    run([sys.executable, "scripts/verify_tensor_core_gemm.py"])
    run([sys.executable, "scripts/verify_persistent_kernels.py"])
    run([sys.executable, "scripts/verify_parallel_primitives.py"])
    run([sys.executable, "scripts/verify_custom_ops.py"])
    run([sys.executable, "scripts/verify_autotune_db.py"])
    run([sys.executable, "scripts/verify_model_integration.py"])
    run([sys.executable, "scripts/verify_serving_traces.py"])
    run([sys.executable, "scripts/verify_kv_cache_paged_attention.py"])
    run([sys.executable, "scripts/verify_attention_serving_stack.py"])
    run([sys.executable, "scripts/verify_flash_attention_backward.py"])
    run([sys.executable, "scripts/verify_sparse_attention_kernels.py"])
    run([sys.executable, "scripts/verify_fused_training_kernels.py"])
    run([sys.executable, "scripts/verify_serving_engine_comparison.py"])
    run([sys.executable, "scripts/verify_speculative_decoding_serving.py"])
    run([sys.executable, "scripts/verify_distributed_topology.py"])
    run([sys.executable, "scripts/verify_distributed_collectives.py"])
    run([sys.executable, "scripts/verify_distributed_collectives_benchmark.py"])
    run([sys.executable, "scripts/verify_distributed_training_optimizer.py"])
    run([sys.executable, "scripts/verify_moe_routing_all_to_all.py"])
    run([sys.executable, "scripts/verify_hardware_capacity_plan.py"])
    run([sys.executable, "scripts/verify_quantization_memory_formats.py"])
    run([sys.executable, "scripts/verify_numerical_reproducibility.py"])
    run([sys.executable, "scripts/verify_cuda_graphs_latency.py"])
    run([sys.executable, "scripts/verify_multi_tenant_gpu_scheduling.py"])
    run([sys.executable, "scripts/verify_regression_ledger.py"])
    run([sys.executable, "scripts/verify_gpu_promotion.py"])
    run([sys.executable, "scripts/verify_gpu_host_preflight.py"])
    run([sys.executable, "scripts/verify_gpu_promotion_suite.py"])
    run([sys.executable, "scripts/lint_gpu_run_imports.py"])
    run([sys.executable, "scripts/verify_gpu_runs.py"])
    run([sys.executable, "scripts/verify_gpu_provenance.py"])
    run([sys.executable, "scripts/verify_gpu_measurement_queue.py"])
    run([sys.executable, "scripts/verify_gpu_acceptance_logic.py"])
    run([sys.executable, "scripts/verify_gpu_handoff.py"])
    run([sys.executable, "scripts/verify_runtime_matrix.py"])
    run([sys.executable, "scripts/verify_profiler_evidence.py"])
    run([sys.executable, "scripts/verify_teaching_pages.py"])
    run([sys.executable, "scripts/verify_worked_walkthroughs.py"])
    run([sys.executable, "scripts/verify_assessment.py"])
    run([sys.executable, "scripts/verify_assessment_grading.py"])
    run([sys.executable, "scripts/verify_capstone_acceptance.py"])
    run([sys.executable, "scripts/verify_advanced_phase.py"])


if __name__ == "__main__":
    main()
